spring:
  application:
    name: product-service
  config:
    import: "configserver:http://localhost:8888"
  kafka:
    bootstrap-servers: localhost:9093
  ai:
    model:
      embedding:
        text: vertexai
    vertex:
      ai:
        embedding:
          project-id: gen-lang-client-0858695901
          location: "asia-east1"
          text:
            options:
              model: "text-embedding-004"
