--
-- PostgreSQL database dump
--

\restrict EafiWXFgfyZ4Er9vNAgOYR4bRfRSZN3kvULfnJjMhTgnYjQBR1tqpwWgJyhgMR8

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg12+1)
-- Dumped by pg_dump version 17.7 (Debian 17.7-3.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.inventory_transactions DROP CONSTRAINT IF EXISTS fkr7t3nlrgle6438pr92jfl4n8s;
ALTER TABLE IF EXISTS ONLY public.stock_reservations DROP CONSTRAINT IF EXISTS fkll6jqseay44u79riia9jldht;
DROP INDEX IF EXISTS public.idx_transaction_type;
DROP INDEX IF EXISTS public.idx_transaction_inventory;
DROP INDEX IF EXISTS public.idx_transaction_created;
DROP INDEX IF EXISTS public.idx_reservation_status;
DROP INDEX IF EXISTS public.idx_reservation_inventory;
DROP INDEX IF EXISTS public.idx_reservation_expires;
DROP INDEX IF EXISTS public.idx_reservation_cart;
DROP INDEX IF EXISTS public.idx_inventory_sku;
DROP INDEX IF EXISTS public.idx_inventory_product;
ALTER TABLE IF EXISTS ONLY public.stock_reservations DROP CONSTRAINT IF EXISTS stock_reservations_pkey;
ALTER TABLE IF EXISTS ONLY public.inventory_transactions DROP CONSTRAINT IF EXISTS inventory_transactions_pkey;
ALTER TABLE IF EXISTS ONLY public.inventory DROP CONSTRAINT IF EXISTS inventory_pkey;
ALTER TABLE IF EXISTS ONLY public.inventory DROP CONSTRAINT IF EXISTS idx_inventory_variant;
DROP TABLE IF EXISTS public.stock_reservations;
DROP TABLE IF EXISTS public.inventory_transactions;
DROP TABLE IF EXISTS public.inventory;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: inventory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory (
    id bigint NOT NULL,
    available_stock integer NOT NULL,
    created_at timestamp(6) without time zone,
    low_stock_threshold integer,
    product_id bigint NOT NULL,
    reorder_point integer,
    reorder_quantity integer,
    reserved_stock integer NOT NULL,
    sku character varying(100),
    total_stock integer NOT NULL,
    track_inventory boolean,
    updated_at timestamp(6) without time zone,
    variant_id bigint NOT NULL,
    version bigint
);


--
-- Name: inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    performed_by bigint,
    quantity_change integer NOT NULL,
    reason text,
    reference_id character varying(100),
    reference_type character varying(50),
    stock_after integer NOT NULL,
    stock_before integer NOT NULL,
    type character varying(20) NOT NULL,
    inventory_id bigint NOT NULL,
    CONSTRAINT inventory_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['SALE'::character varying, 'ADJUSTMENT'::character varying, 'RESERVATION'::character varying, 'RELEASE'::character varying, 'PURCHASE'::character varying, 'RETURN'::character varying, 'INITIAL'::character varying])::text[])))
);


--
-- Name: inventory_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventory_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_reservations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_reservations (
    id bigint NOT NULL,
    cancelled_at timestamp(6) without time zone,
    cart_id bigint,
    confirmed_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    quantity integer NOT NULL,
    reserved_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    user_id bigint,
    inventory_id bigint NOT NULL,
    CONSTRAINT stock_reservations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: stock_reservations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: inventory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.inventory (id, available_stock, created_at, low_stock_threshold, product_id, reorder_point, reorder_quantity, reserved_stock, sku, total_stock, track_inventory, updated_at, variant_id, version) FROM stdin;
1	40	2026-02-04 21:00:24.602822	10	1	5	50	0	SKU-IPHONE17-XANH	40	t	2026-02-04 21:00:24.602822	1	0
2	12	2026-02-04 21:00:32.311466	10	1	5	50	0	SKU-1221	12	t	2026-02-04 21:00:32.311466	2	0
3	12	2026-02-04 21:00:41.054594	10	2	5	50	0	SKU-12266	12	t	2026-02-04 21:00:41.054594	3	0
4	12	2026-02-04 21:00:47.565227	10	2	5	50	0	SKU-12268	12	t	2026-02-04 21:00:47.565227	4	0
5	12	2026-02-04 21:00:55.536339	10	2	5	50	0	SKU-12288	12	t	2026-02-04 21:00:55.536339	5	0
6	33	2026-02-04 21:01:02.787211	10	3	5	50	0	SKU-122699	33	t	2026-02-04 21:01:02.787211	6	0
7	33	2026-02-04 21:01:09.545795	10	3	5	50	0	SKU-122600	33	t	2026-02-04 21:01:09.545795	7	0
9	9	2026-03-10 12:44:41.990283	10	4	5	50	0	SKU-DARKBROWN	9	t	2026-03-10 12:44:41.990283	9	0
10	12	2026-03-10 12:46:02.725107	10	4	5	50	0	SKU-DARKGREEN	12	t	2026-03-10 12:46:02.725107	10	0
47	12	2026-03-23 08:51:03.69472	10	28	5	50	0	SKU-CQI	12	t	2026-03-23 08:51:03.69472	55	0
48	12	2026-03-23 08:51:08.538766	10	28	5	50	0	SKU-CQO	12	t	2026-03-23 08:51:08.538766	56	0
49	12	2026-03-23 08:54:01.947329	10	29	5	50	0	SKU-CQP	12	t	2026-03-23 08:54:01.947329	59	0
20	7	2026-03-23 08:09:11.67898	10	18	5	50	0	SKU-CCW	7	t	2026-05-12 14:17:21.457564	20	4
51	111	2026-06-07 13:08:04.529414	10	31	5	50	0	SKU-CCVG	111	t	2026-06-07 13:08:04.529414	62	0
13	19	2026-03-23 07:48:20.412051	10	14	5	50	0	SKU-GHJ	19	t	2026-06-07 13:35:22.123725	13	2
52	10000	2026-06-07 13:38:57.747905	10	32	5	50	0	SKU-CCOasdasdasd	10000	t	2026-06-07 13:38:57.747905	64	0
38	10	2026-03-23 08:33:01.080853	10	23	5	50	0	SKU-CCV	10	t	2026-03-31 17:54:43.92894	44	2
14	125	2026-03-23 07:50:49.143742	111	15	5	50	0	SKU-VBN	125	t	2026-06-07 10:00:52.584284	14	12
8	4	2026-03-10 12:43:58.042944	10	4	5	50	0	SKU-COCOABROWN	4	t	2026-03-21 09:22:30.42129	8	13
12	12	2026-03-23 07:48:11.983264	10	14	5	50	0	SKU-QWE	12	t	2026-03-23 07:48:11.983612	12	0
15	12	2026-03-23 07:55:00.115658	10	16	5	50	0	SKU-CCC	12	t	2026-03-23 07:55:00.115658	15	0
16	12	2026-03-23 07:59:42.109495	10	17	5	50	0	SKU-CAC	12	t	2026-03-23 07:59:42.109495	16	0
17	12	2026-03-23 07:59:48.048986	10	17	5	50	0	SKU-CCG	12	t	2026-03-23 07:59:48.048986	17	0
18	12	2026-03-23 07:59:54.01903	10	17	5	50	0	SKU-CCQ	12	t	2026-03-23 07:59:54.01903	18	0
19	12	2026-03-23 08:00:00.417361	10	17	5	50	0	SKU-CCN	12	t	2026-03-23 08:00:00.417361	19	0
21	12	2026-03-23 08:09:16.348306	10	18	5	50	0	SKU-CCE	12	t	2026-03-23 08:09:16.348306	21	0
22	12	2026-03-23 08:09:21.344843	10	18	5	50	0	SKU-CCR	12	t	2026-03-23 08:09:21.344843	23	0
23	12	2026-03-23 08:09:26.869663	10	18	5	50	0	SKU-CCT	12	t	2026-03-23 08:09:26.869663	25	0
24	12	2026-03-23 08:14:00.459267	10	19	5	50	0	SKU-CCY	12	t	2026-03-23 08:14:00.459267	26	0
25	12	2026-03-23 08:14:05.902603	10	19	5	50	0	SKU-CCU	12	t	2026-03-23 08:14:05.902603	27	0
26	12	2026-03-23 08:14:16.966483	10	19	5	50	0	SKU-CCI	12	t	2026-03-23 08:14:16.966483	28	0
27	12	2026-03-23 08:19:30.236569	10	20	5	50	0	SKU-CCO	12	t	2026-03-23 08:19:30.236569	29	0
28	12	2026-03-23 08:19:36.425535	10	20	5	50	0	SKU-CCP	12	t	2026-03-23 08:19:36.425535	30	0
29	12	2026-03-23 08:19:41.554086	10	20	5	50	0	SKU-CCS	12	t	2026-03-23 08:19:41.554086	31	0
30	12	2026-03-23 08:19:48.934642	10	20	5	50	0	SKU-CCD	12	t	2026-03-23 08:19:48.934642	32	0
31	12	2026-03-23 08:19:58.140432	10	20	5	50	0	SKU-CCF	12	t	2026-03-23 08:19:58.140432	33	0
32	12	2026-03-23 08:25:45.429142	10	21	5	50	0	SKU-CCH	12	t	2026-03-23 08:25:45.429142	37	0
33	12	2026-03-23 08:25:50.517349	10	21	5	50	0	SKU-CCJ	12	t	2026-03-23 08:25:50.517349	38	0
34	12	2026-03-23 08:25:55.396481	10	21	5	50	0	SKU-CCK	12	t	2026-03-23 08:25:55.396481	39	0
35	12	2026-03-23 08:26:02.84217	10	21	5	50	0	SKU-CCL	12	t	2026-03-23 08:26:02.84217	40	0
36	12	2026-03-23 08:29:55.71608	10	22	5	50	0	SKU-CCZ	12	t	2026-03-23 08:29:55.71608	41	0
37	12	2026-03-23 08:30:00.132793	10	22	5	50	0	SKU-CCX	12	t	2026-03-23 08:30:00.132793	42	0
39	12	2026-03-23 08:33:07.090684	10	23	5	50	0	SKU-CCB	12	t	2026-03-23 08:33:07.090684	45	0
40	12	2026-03-23 08:38:25.230864	10	24	5	50	0	SKU-CCM	12	t	2026-03-23 08:38:25.230864	47	0
41	12	2026-03-23 08:40:12.702197	10	25	5	50	0	SKU-CQW	12	t	2026-03-23 08:40:12.702197	48	0
42	12	2026-03-23 08:42:54.438479	10	26	5	50	0	SKU-CQE	12	t	2026-03-23 08:42:54.438479	49	0
43	12	2026-03-23 08:48:01.332022	10	27	5	50	0	SKU-CQR	12	t	2026-03-23 08:48:01.332022	50	0
44	12	2026-03-23 08:48:06.129128	10	27	5	50	0	SKU-CQT	12	t	2026-03-23 08:48:06.129128	51	0
45	12	2026-03-23 08:48:10.769515	10	27	5	50	0	SKU-CQY	12	t	2026-03-23 08:48:10.769515	52	0
46	12	2026-03-23 08:50:58.560905	10	28	5	50	0	SKU-CQU	12	t	2026-03-23 08:50:58.560905	54	0
50	6	2026-03-23 08:54:07.964091	10	29	5	50	0	SKU-CQA	6	t	2026-04-19 19:36:54.288368	60	3
11	116	2026-03-23 07:47:59.701127	10	14	5	50	0	sku-ASDAS	116	t	2026-06-07 12:42:35.606221	11	5
\.


--
-- Data for Name: inventory_transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.inventory_transactions (id, created_at, performed_by, quantity_change, reason, reference_id, reference_type, stock_after, stock_before, type, inventory_id) FROM stdin;
1	2026-02-04 21:00:24.658113	\N	40	Initial stock from migration	\N	MIGRATION	40	0	INITIAL	1
2	2026-02-04 21:00:32.314638	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	2
3	2026-02-04 21:00:41.061383	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	3
4	2026-02-04 21:00:47.568574	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	4
5	2026-02-04 21:00:55.539119	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	5
6	2026-02-04 21:01:02.79077	\N	33	Initial stock from migration	\N	MIGRATION	33	0	INITIAL	6
7	2026-02-04 21:01:09.549003	\N	33	Initial stock from migration	\N	MIGRATION	33	0	INITIAL	7
8	2026-03-10 12:43:58.094087	\N	20	Initial stock from migration	\N	MIGRATION	20	0	INITIAL	8
9	2026-03-10 12:44:41.992956	\N	9	Initial stock from migration	\N	MIGRATION	9	0	INITIAL	9
10	2026-03-10 12:46:02.731645	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	10
11	2026-03-10 12:56:16.015042	\N	-1	Order OG-1773122175704-04C14436	OG-1773122175704-04C14436	ORDER	19	20	SALE	8
12	2026-03-10 12:59:21.589432	\N	-1	Order OG-1773122361554-395CB7E7	OG-1773122361554-395CB7E7	ORDER	18	19	SALE	8
13	2026-03-12 14:06:24.514702	\N	-2	Order OG-1773299184223-2AECE61F	OG-1773299184223-2AECE61F	ORDER	16	18	SALE	8
14	2026-03-13 11:21:18.873309	\N	-1	Order OG-1773375678402-EF86201F	OG-1773375678402-EF86201F	ORDER	15	16	SALE	8
15	2026-03-13 21:42:18.686144	\N	-1	Order OG-1773412938014-F5A154B1	OG-1773412938014-F5A154B1	ORDER	14	15	SALE	8
16	2026-03-19 13:12:02.546233	\N	-1	Order OG-1773900722157-426EAB1E	OG-1773900722157-426EAB1E	ORDER	13	14	SALE	8
17	2026-03-19 13:13:40.152287	\N	-1	Order OG-1773900820118-7BB17C9D	OG-1773900820118-7BB17C9D	ORDER	12	13	SALE	8
18	2026-03-19 19:26:46.989228	\N	-1	Order OG-1773923206707-137D0E98	OG-1773923206707-137D0E98	ORDER	11	12	SALE	8
19	2026-03-20 16:43:30.7361	\N	-1	Order OG-1773999810338-988D30EC	OG-1773999810338-988D30EC	ORDER	10	11	SALE	8
20	2026-03-20 17:36:00.12376	\N	-2	Order OG-1774002960013-1F60F297	OG-1774002960013-1F60F297	ORDER	8	10	SALE	8
21	2026-03-20 17:36:49.214451	\N	-2	Order OG-1774003009162-6634ADB3	OG-1774003009162-6634ADB3	ORDER	6	8	SALE	8
22	2026-03-20 20:23:37.491603	\N	-1	Order OG-1774013017373-F62AFC8C	OG-1774013017373-F62AFC8C	ORDER	5	6	SALE	8
23	2026-03-21 09:22:29.861391	\N	-1	Order OG-1774059749378-8343D1B7	OG-1774059749378-8343D1B7	ORDER	4	5	SALE	8
24	2026-03-23 07:47:59.73612	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	11
25	2026-03-23 07:48:11.989529	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	12
26	2026-03-23 07:48:20.416359	\N	10	Initial stock from migration	\N	MIGRATION	10	0	INITIAL	13
27	2026-03-23 07:50:49.147501	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	14
28	2026-03-23 07:55:00.119374	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	15
29	2026-03-23 07:59:42.113533	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	16
30	2026-03-23 07:59:48.052789	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	17
31	2026-03-23 07:59:54.023612	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	18
32	2026-03-23 08:00:00.421114	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	19
33	2026-03-23 08:09:11.683065	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	20
34	2026-03-23 08:09:16.352087	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	21
35	2026-03-23 08:09:21.348862	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	22
36	2026-03-23 08:09:26.873379	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	23
37	2026-03-23 08:14:00.462401	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	24
38	2026-03-23 08:14:05.905172	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	25
39	2026-03-23 08:14:16.969566	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	26
40	2026-03-23 08:19:30.239755	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	27
41	2026-03-23 08:19:36.428837	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	28
42	2026-03-23 08:19:41.556746	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	29
43	2026-03-23 08:19:48.937351	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	30
44	2026-03-23 08:19:58.143131	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	31
45	2026-03-23 08:25:45.432965	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	32
46	2026-03-23 08:25:50.521145	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	33
47	2026-03-23 08:25:55.399192	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	34
48	2026-03-23 08:26:02.844784	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	35
49	2026-03-23 08:29:55.71941	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	36
50	2026-03-23 08:30:00.134897	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	37
51	2026-03-23 08:33:01.084857	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	38
52	2026-03-23 08:33:07.093818	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	39
53	2026-03-23 08:38:25.233541	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	40
54	2026-03-23 08:40:12.708558	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	41
55	2026-03-23 08:42:54.441182	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	42
56	2026-03-23 08:48:01.334926	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	43
57	2026-03-23 08:48:06.132245	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	44
58	2026-03-23 08:48:10.773321	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	45
59	2026-03-23 08:50:58.563589	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	46
60	2026-03-23 08:51:03.698733	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	47
61	2026-03-23 08:51:08.541913	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	48
62	2026-03-23 08:54:01.950503	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	49
63	2026-03-23 08:54:07.967895	\N	12	Initial stock from migration	\N	MIGRATION	12	0	INITIAL	50
64	2026-03-27 11:34:29.164905	\N	-1	Order OG-1774586068558-057C8650	OG-1774586068558-057C8650	ORDER	11	12	SALE	38
65	2026-03-27 11:48:35.781696	\N	-1	Order OG-1774586915311-3E6A005C	OG-1774586915311-3E6A005C	ORDER	11	12	SALE	11
66	2026-03-29 12:28:25.883969	\N	-1	Order OG-1774762105518-5A777F80	OG-1774762105518-5A777F80	ORDER	11	12	SALE	14
67	2026-03-29 14:41:27.230233	\N	-1	Order OG-1774770087141-76440FF2	OG-1774770087141-76440FF2	ORDER	10	11	SALE	14
68	2026-03-31 17:54:43.066701	\N	-1	Order OG-1774954482638-08CA053B	OG-1774954482638-08CA053B	ORDER	11	12	SALE	20
69	2026-03-31 17:54:43.783189	\N	-1	Order OG-1774954482638-08CA053B	OG-1774954482638-08CA053B	ORDER	10	11	SALE	38
70	2026-04-02 18:24:06.556389	\N	-1	Order OG-1775128991384-CD122001	OG-1775128991384-CD122001	ORDER	10	11	SALE	20
71	2026-04-02 18:24:06.910309	\N	-3	Order OG-1775128991384-CD122001	OG-1775128991384-CD122001	ORDER	9	12	SALE	50
72	2026-04-07 20:24:04.752149	\N	-1	Order OG-1775568244311-E2364838	OG-1775568244311-E2364838	ORDER	10	11	SALE	11
73	2026-04-07 20:26:06.733052	\N	-1	Order OG-1775568366695-22618DE0	OG-1775568366695-22618DE0	ORDER	9	10	SALE	14
74	2026-04-07 21:21:56.743286	\N	-1	Order OG-1775571716481-DC59A963	OG-1775571716481-DC59A963	ORDER	8	9	SALE	50
75	2026-04-07 21:22:24.935531	\N	-1	Order OG-1775571744905-3A6728F5	OG-1775571744905-3A6728F5	ORDER	8	9	SALE	14
76	2026-04-07 21:50:06.208971	\N	-1	Order OG-1775573405891-93285231	OG-1775573405891-93285231	ORDER	7	8	SALE	14
77	2026-04-07 21:52:35.809145	\N	-1	Order OG-1775573555745-62BC5EB6	OG-1775573555745-62BC5EB6	ORDER	6	7	SALE	14
78	2026-04-19 19:36:53.818289	\N	-1	Order OG-1776602183347-C19F62CB	OG-1776602183347-C19F62CB	ORDER	9	10	SALE	20
79	2026-04-19 19:36:54.276864	\N	-2	Order OG-1776602183347-C19F62CB	OG-1776602183347-C19F62CB	ORDER	6	8	SALE	50
80	2026-04-19 20:42:53.727246	\N	-1	Order OG-1776606173358-DA601969	OG-1776606173358-DA601969	ORDER	5	6	SALE	14
81	2026-04-19 20:44:32.834031	\N	-1	Order OG-1776606272804-2C433603	OG-1776606272804-2C433603	ORDER	4	5	SALE	14
82	2026-05-12 14:17:20.827687	\N	-2	Order OG-1778570240366-1C320818	OG-1778570240366-1C320818	ORDER	7	9	SALE	20
83	2026-05-12 14:24:21.691166	\N	-1	Order OG-1778570661645-9F7143E6	OG-1778570661645-9F7143E6	ORDER	3	4	SALE	14
84	2026-06-07 10:00:18.125217	102	111	Manual add	\N	MANUAL	121	10	ADJUSTMENT	11
85	2026-06-07 10:00:42.647304	102	11	Manual add	\N	MANUAL	21	10	ADJUSTMENT	13
86	2026-06-07 10:00:47.869905	102	11	Manual add	\N	MANUAL	14	3	ADJUSTMENT	14
87	2026-06-07 10:00:52.578209	102	111	Manual add	\N	MANUAL	125	14	ADJUSTMENT	14
88	2026-06-07 10:02:03.961386	\N	-1	Order OG-1780801323495-E7662050	OG-1780801323495-E7662050	ORDER	120	121	SALE	11
89	2026-06-07 12:42:35.591298	\N	-4	Order OG-1780810955512-76E99340	OG-1780810955512-76E99340	ORDER	116	120	SALE	11
90	2026-06-07 13:08:04.537695	\N	111	Initial stock from migration	\N	MIGRATION	111	0	INITIAL	51
91	2026-06-07 13:35:22.10882	\N	-2	Order OG-1780814122056-EEB7A3D7	OG-1780814122056-EEB7A3D7	ORDER	19	21	SALE	13
92	2026-06-07 13:38:57.751186	\N	10000	Initial stock from migration	\N	MIGRATION	10000	0	INITIAL	52
\.


--
-- Data for Name: stock_reservations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.stock_reservations (id, cancelled_at, cart_id, confirmed_at, expires_at, quantity, reserved_at, status, user_id, inventory_id) FROM stdin;
\.


--
-- Name: inventory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.inventory_id_seq', 52, true);


--
-- Name: inventory_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.inventory_transactions_id_seq', 92, true);


--
-- Name: stock_reservations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.stock_reservations_id_seq', 1, false);


--
-- Name: inventory idx_inventory_variant; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT idx_inventory_variant UNIQUE (variant_id);


--
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (id);


--
-- Name: inventory_transactions inventory_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_transactions
    ADD CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id);


--
-- Name: stock_reservations stock_reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_reservations
    ADD CONSTRAINT stock_reservations_pkey PRIMARY KEY (id);


--
-- Name: idx_inventory_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inventory_product ON public.inventory USING btree (product_id);


--
-- Name: idx_inventory_sku; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inventory_sku ON public.inventory USING btree (sku);


--
-- Name: idx_reservation_cart; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservation_cart ON public.stock_reservations USING btree (cart_id);


--
-- Name: idx_reservation_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservation_expires ON public.stock_reservations USING btree (expires_at);


--
-- Name: idx_reservation_inventory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservation_inventory ON public.stock_reservations USING btree (inventory_id);


--
-- Name: idx_reservation_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reservation_status ON public.stock_reservations USING btree (status);


--
-- Name: idx_transaction_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_created ON public.inventory_transactions USING btree (created_at);


--
-- Name: idx_transaction_inventory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_inventory ON public.inventory_transactions USING btree (inventory_id);


--
-- Name: idx_transaction_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_type ON public.inventory_transactions USING btree (type);


--
-- Name: stock_reservations fkll6jqseay44u79riia9jldht; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_reservations
    ADD CONSTRAINT fkll6jqseay44u79riia9jldht FOREIGN KEY (inventory_id) REFERENCES public.inventory(id);


--
-- Name: inventory_transactions fkr7t3nlrgle6438pr92jfl4n8s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_transactions
    ADD CONSTRAINT fkr7t3nlrgle6438pr92jfl4n8s FOREIGN KEY (inventory_id) REFERENCES public.inventory(id);


--
-- PostgreSQL database dump complete
--

\unrestrict EafiWXFgfyZ4Er9vNAgOYR4bRfRSZN3kvULfnJjMhTgnYjQBR1tqpwWgJyhgMR8

