--
-- PostgreSQL database dump
--

\restrict aPizkY4O3qG8a8D7l4jF3vejqbJe8AXAva4IFoZyvAPLHiy8kMHtoIU63t8EhD1

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg12+1)
-- Dumped by pg_dump version 17.7 (Debian 17.7-3.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.payment_transactions DROP CONSTRAINT IF EXISTS fkspqd5e2tfb9aoj9l4a02ruq7h;
ALTER TABLE IF EXISTS ONLY public.cart_items DROP CONSTRAINT IF EXISTS fkpcttvuq4mxppo8sxggjtn5i2c;
ALTER TABLE IF EXISTS ONLY public.sub_orders DROP CONSTRAINT IF EXISTS fk8noullt4k2ydiwck3ivi0jxi3;
ALTER TABLE IF EXISTS ONLY public.sub_order_items DROP CONSTRAINT IF EXISTS fk5v0m24lqb26wr46210sdxhduu;
ALTER TABLE IF EXISTS ONLY public.payment_transactions DROP CONSTRAINT IF EXISTS ukohtafpfcbxdd1lweogsh93jd1;
ALTER TABLE IF EXISTS ONLY public.cart_items DROP CONSTRAINT IF EXISTS ukia0vdyyx8cilyaysrssqqj0bp;
ALTER TABLE IF EXISTS ONLY public.carts DROP CONSTRAINT IF EXISTS uk64t7ox312pqal3p7fg9o503c2;
ALTER TABLE IF EXISTS ONLY public.sub_orders DROP CONSTRAINT IF EXISTS uk1lmiax0oo7xx3iqet7jajspwt;
ALTER TABLE IF EXISTS ONLY public.order_groups DROP CONSTRAINT IF EXISTS uk11h1w6usmwikh6t759mqhbhj8;
ALTER TABLE IF EXISTS ONLY public.sub_orders DROP CONSTRAINT IF EXISTS sub_orders_pkey;
ALTER TABLE IF EXISTS ONLY public.sub_order_items DROP CONSTRAINT IF EXISTS sub_order_items_pkey;
ALTER TABLE IF EXISTS ONLY public.payment_transactions DROP CONSTRAINT IF EXISTS payment_transactions_pkey;
ALTER TABLE IF EXISTS ONLY public.order_groups DROP CONSTRAINT IF EXISTS order_groups_pkey;
ALTER TABLE IF EXISTS ONLY public.carts DROP CONSTRAINT IF EXISTS carts_pkey;
ALTER TABLE IF EXISTS ONLY public.cart_items DROP CONSTRAINT IF EXISTS cart_items_pkey;
DROP TABLE IF EXISTS public.sub_orders;
DROP TABLE IF EXISTS public.sub_order_items;
DROP TABLE IF EXISTS public.payment_transactions;
DROP TABLE IF EXISTS public.order_groups;
DROP TABLE IF EXISTS public.carts;
DROP TABLE IF EXISTS public.cart_items;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    item_id bigint NOT NULL,
    added_at timestamp(6) without time zone NOT NULL,
    price numeric(10,2) NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    variant_id bigint,
    cart_id bigint NOT NULL
);


--
-- Name: cart_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts (
    cart_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone,
    session_id character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: carts_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carts ALTER COLUMN cart_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_groups (
    group_id bigint NOT NULL,
    applied_product_voucher_id bigint,
    applied_shipping_voucher_id bigint,
    billing_address_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(3) NOT NULL,
    discount_amount numeric(10,2),
    group_number character varying(50) NOT NULL,
    notes text,
    overall_status character varying(50) NOT NULL,
    payment_status character varying(50) NOT NULL,
    shipping_address_id bigint NOT NULL,
    shipping_cost numeric(10,2),
    tax_amount numeric(10,2),
    total_amount numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT order_groups_overall_status_check CHECK (((overall_status)::text = ANY ((ARRAY['PAID'::character varying, 'PROCESSING'::character varying, 'PARTIALLY_SHIPPED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'PARTIALLY_REFUNDED'::character varying, 'FULLY_REFUNDED'::character varying])::text[]))),
    CONSTRAINT order_groups_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['SUCCEEDED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'PARTIALLY_REFUNDED'::character varying, 'FULLY_REFUNDED'::character varying])::text[])))
);


--
-- Name: order_groups_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_groups ALTER COLUMN group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_groups_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_transactions (
    transaction_id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(3) NOT NULL,
    error_code character varying(100),
    error_message text,
    idempotency_key character varying(255) NOT NULL,
    metadata text,
    payment_method character varying(50) NOT NULL,
    provider character varying(50) NOT NULL,
    provider_transaction_id character varying(255),
    status character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    group_id bigint NOT NULL,
    CONSTRAINT payment_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['SUCCEEDED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying, 'PARTIALLY_REFUNDED'::character varying, 'FULLY_REFUNDED'::character varying])::text[])))
);


--
-- Name: payment_transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_transactions ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_transactions_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sub_order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sub_order_items (
    item_id bigint NOT NULL,
    image_url character varying(255),
    product_id bigint NOT NULL,
    product_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    total_price numeric(10,2) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    variant_id bigint,
    variant_name character varying(255),
    sub_order_id bigint NOT NULL
);


--
-- Name: sub_order_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sub_order_items ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sub_order_items_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sub_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sub_orders (
    sub_order_id bigint NOT NULL,
    cancelled_at timestamp(6) without time zone,
    carrier character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    delivered_at timestamp(6) without time zone,
    discount numeric(10,2),
    estimated_delivery date,
    fulfillment_status character varying(50),
    ghn_order_code character varying(50),
    seller_id bigint NOT NULL,
    seller_name character varying(255) NOT NULL,
    shipped_at timestamp(6) without time zone,
    shipping_cost numeric(10,2),
    status character varying(50) NOT NULL,
    sub_order_number character varying(50) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    tax numeric(10,2),
    total numeric(10,2) NOT NULL,
    tracking_number character varying(100),
    tracking_url character varying(500),
    updated_at timestamp(6) without time zone NOT NULL,
    group_id bigint NOT NULL,
    CONSTRAINT sub_orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'READY_TO_PICK'::character varying, 'PICKING'::character varying, 'PICKED'::character varying, 'SHIPPED'::character varying, 'STORING'::character varying, 'TRANSPORTING'::character varying, 'SORTING'::character varying, 'DELIVERING'::character varying, 'DELIVERED'::character varying, 'DELIVERY_FAIL'::character varying, 'WAITING_TO_RETURN'::character varying, 'RETURNING'::character varying, 'RETURNED'::character varying, 'CANCELLED'::character varying, 'REFUND_PENDING'::character varying, 'REFUNDED'::character varying, 'EXCEPTION'::character varying, 'LOST'::character varying, 'DAMAGE'::character varying])::text[])))
);


--
-- Name: sub_orders_sub_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sub_orders ALTER COLUMN sub_order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sub_orders_sub_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cart_items (item_id, added_at, price, product_id, quantity, variant_id, cart_id) FROM stdin;
7	2026-03-29 14:28:53.899502	1000000.00	22	1	41	4
24	2026-04-19 21:03:26.733824	38499000.00	3	1	6	1
26	2026-04-19 21:10:19.02355	2000000.00	29	1	60	7
27	2026-04-19 21:13:59.763458	200000.00	27	1	51	7
28	2026-04-19 21:14:03.066344	1000000.00	28	1	56	7
33	2026-06-07 12:40:55.666242	22222.00	14	3	11	9
\.


--
-- Data for Name: carts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.carts (cart_id, created_at, expires_at, session_id, updated_at, user_id) FROM stdin;
1	2026-03-23 06:57:25.784608	2026-04-22 06:57:25.69054	\N	2026-03-23 06:57:25.784608	1
2	2026-03-23 07:13:27.042315	2026-04-22 07:13:27.041265	\N	2026-03-23 07:13:27.042315	102
3	2026-03-23 08:02:40.71196	2026-04-22 08:02:40.709781	\N	2026-03-23 08:02:40.71196	105
4	2026-03-23 08:21:22.794816	2026-04-22 08:21:22.794308	\N	2026-03-23 08:21:22.794816	106
5	2026-03-23 08:35:37.972506	2026-04-22 08:35:37.970998	\N	2026-03-23 08:35:37.972506	107
6	2026-03-23 08:44:08.997498	2026-04-22 08:44:08.99647	\N	2026-03-23 08:44:08.997498	108
7	2026-04-19 21:06:34.749255	2026-05-19 21:06:34.748721	\N	2026-04-19 21:06:34.749255	109
8	2026-05-12 13:44:47.841274	2026-06-11 13:44:47.782326	\N	2026-05-12 13:44:47.841274	112
9	2026-06-07 12:40:08.346187	2026-07-07 12:40:08.336892	\N	2026-06-07 12:40:08.346187	113
10	2026-06-07 13:33:31.289279	2026-07-07 13:33:31.284588	\N	2026-06-07 13:33:31.289279	116
\.


--
-- Data for Name: order_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_groups (group_id, applied_product_voucher_id, applied_shipping_voucher_id, billing_address_id, created_at, currency, discount_amount, group_number, notes, overall_status, payment_status, shipping_address_id, shipping_cost, tax_amount, total_amount, updated_at, user_id) FROM stdin;
1	\N	\N	\N	2026-03-27 11:34:28.564194	USD	0.00	OG-1774586068558-057C8650	\N	PAID	SUCCEEDED	188	99000.00	19900.00	218900.00	2026-03-27 11:34:28.564194	1
2	\N	\N	\N	2026-03-27 11:48:35.323193	USD	0.00	OG-1774586915311-3E6A005C	\N	COMPLETED	SUCCEEDED	189	99000.00	12122.20	133344.20	2026-03-27 11:49:22.325022	102
3	\N	\N	\N	2026-03-29 12:28:25.521273	USD	0.00	OG-1774762105518-5A777F80	\N	COMPLETED	SUCCEEDED	189	99000.00	11000.00	121000.00	2026-03-29 12:28:54.232811	102
4	\N	\N	\N	2026-03-29 14:41:27.142831	USD	0.00	OG-1774770087141-76440FF2	\N	PAID	SUCCEEDED	188	99000.00	11000.00	121000.00	2026-03-29 14:41:27.142831	1
5	\N	\N	\N	2026-03-31 17:54:42.64279	USD	0.00	OG-1774954482638-08CA053B	\N	PAID	SUCCEEDED	189	99000.00	29900.00	328900.00	2026-03-31 17:54:42.64279	102
6	\N	\N	\N	2026-04-02 18:23:11.386716	VND	0.00	OG-1775128991384-CD122001	\N	PAID	SUCCEEDED	188	129500.00	622950.00	6852450.00	2026-04-02 18:23:11.386716	1
7	\N	\N	\N	2026-04-07 20:24:04.313929	VND	0.00	OG-1775568244311-E2364838	\N	COMPLETED	SUCCEEDED	189	99000.00	12122.20	133344.20	2026-04-07 20:24:44.602466	102
8	\N	\N	\N	2026-04-07 20:26:06.695633	VND	0.00	OG-1775568366695-22618DE0	\N	COMPLETED	SUCCEEDED	189	99000.00	11000.00	121000.00	2026-04-07 20:26:28.294759	102
9	\N	\N	\N	2026-04-07 21:21:56.484951	VND	0.00	OG-1775571716481-DC59A963	\N	PAID	SUCCEEDED	189	109000.00	210900.00	2319900.00	2026-04-07 21:21:56.484951	102
10	\N	\N	\N	2026-04-07 21:22:24.905899	VND	0.00	OG-1775571744905-3A6728F5	\N	COMPLETED	SUCCEEDED	189	99000.00	11000.00	121000.00	2026-04-07 21:22:39.377006	102
11	\N	\N	\N	2026-04-07 21:50:05.893326	VND	0.00	OG-1775573405891-93285231	\N	COMPLETED	SUCCEEDED	189	99000.00	11000.00	121000.00	2026-04-07 21:50:35.326526	102
12	\N	\N	\N	2026-04-07 21:52:35.74779	VND	0.00	OG-1775573555745-62BC5EB6	\N	COMPLETED	SUCCEEDED	189	99000.00	11000.00	121000.00	2026-04-07 21:53:08.016401	102
13	\N	\N	\N	2026-04-19 19:36:23.350067	VND	0.00	OG-1776602183347-C19F62CB	\N	PAID	SUCCEEDED	189	119500.00	421950.00	4641450.00	2026-04-19 19:36:23.350067	102
14	\N	\N	\N	2026-04-19 20:42:53.361219	VND	0.00	OG-1776606173358-DA601969	\N	COMPLETED	SUCCEEDED	189	99000.00	11000.00	121000.00	2026-04-19 20:43:21.420313	102
15	\N	\N	\N	2026-04-19 20:44:32.805173	VND	0.00	OG-1776606272804-2C433603	\N	COMPLETED	SUCCEEDED	189	99000.00	11000.00	121000.00	2026-04-19 20:44:50.732663	102
16	\N	\N	\N	2026-05-12 14:17:20.369242	VND	0.00	OG-1778570240366-1C320818	\N	PAID	SUCCEEDED	192	99000.00	29900.00	328900.00	2026-05-12 14:17:20.369242	112
17	\N	\N	\N	2026-05-12 14:24:21.646053	VND	0.00	OG-1778570661645-9F7143E6	\N	COMPLETED	SUCCEEDED	192	99000.00	11000.00	121000.00	2026-05-12 14:33:58.192858	112
18	\N	\N	\N	2026-06-07 10:02:03.49836	VND	0.00	OG-1780801323495-E7662050	\N	COMPLETED	SUCCEEDED	189	99000.00	12122.20	133344.20	2026-06-07 10:02:49.891627	102
19	\N	\N	\N	2026-06-07 12:42:35.515449	VND	0.00	OG-1780810955512-76E99340	\N	COMPLETED	SUCCEEDED	189	99000.00	18788.80	206676.80	2026-06-07 13:08:50.430806	102
20	\N	\N	\N	2026-06-07 13:35:22.057315	VND	0.00	OG-1780814122056-EEB7A3D7	\N	COMPLETED	SUCCEEDED	193	99000.00	12300.00	135300.00	2026-06-07 13:36:39.790529	116
\.


--
-- Data for Name: payment_transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.payment_transactions (transaction_id, amount, completed_at, created_at, currency, error_code, error_message, idempotency_key, metadata, payment_method, provider, provider_transaction_id, status, updated_at, group_id) FROM stdin;
1	218900.00	2026-03-27 11:34:28.665422	2026-03-27 11:34:28.669042	USD	\N	\N	pi_3TFS65BINykhgxy50lA9pp2J	\N	card	stripe	pi_3TFS65BINykhgxy50lA9pp2J	SUCCEEDED	2026-03-27 11:34:28.669042	1
2	133344.20	2026-03-27 11:48:35.424563	2026-03-27 11:48:35.426125	USD	\N	\N	pi_3TFSJkBINykhgxy51zrdSgpF	\N	card	stripe	pi_3TFSJkBINykhgxy51zrdSgpF	SUCCEEDED	2026-03-27 11:48:35.426125	2
3	121000.00	2026-03-29 12:28:25.575126	2026-03-29 12:28:25.57609	USD	\N	\N	pi_3TGBtSBINykhgxy51WBcUjdJ	\N	card	stripe	pi_3TGBtSBINykhgxy51WBcUjdJ	SUCCEEDED	2026-03-29 12:28:25.57609	3
4	121000.00	2026-03-29 14:41:27.180909	2026-03-29 14:41:27.181917	USD	\N	\N	pi_3TGDpPBINykhgxy5038VLfE7	\N	card	stripe	pi_3TGDpPBINykhgxy5038VLfE7	SUCCEEDED	2026-03-29 14:41:27.181917	4
5	328900.00	2026-03-31 17:54:42.727022	2026-03-31 17:54:42.728042	USD	\N	\N	pi_3TGzvIBINykhgxy51yWkgdZO	\N	card	stripe	pi_3TGzvIBINykhgxy51yWkgdZO	SUCCEEDED	2026-03-31 17:54:42.728042	5
6	6852450.00	2026-04-02 18:23:11.459831	2026-04-02 18:23:11.460823	VND	\N	\N	pi_3THjKhBINykhgxy50vZ6Q4kM	\N	card	stripe	pi_3THjKhBINykhgxy50vZ6Q4kM	SUCCEEDED	2026-04-02 18:23:11.460823	6
7	133344.20	2026-04-07 20:24:04.383612	2026-04-07 20:24:04.384607	VND	\N	\N	pi_3TJZbfBINykhgxy50O5Wov93	\N	card	stripe	pi_3TJZbfBINykhgxy50O5Wov93	SUCCEEDED	2026-04-07 20:24:04.384607	7
8	121000.00	2026-04-07 20:26:06.715166	2026-04-07 20:26:06.715738	VND	\N	\N	pi_3TJZdhBINykhgxy50P5z1aUj	\N	card	stripe	pi_3TJZdhBINykhgxy50P5z1aUj	SUCCEEDED	2026-04-07 20:26:06.715738	8
9	2319900.00	2026-04-07 21:21:56.554487	2026-04-07 21:21:56.555485	VND	\N	\N	pi_3TJaVjBINykhgxy51OdYTKsy	\N	card	stripe	pi_3TJaVjBINykhgxy51OdYTKsy	SUCCEEDED	2026-04-07 21:21:56.555485	9
10	121000.00	2026-04-07 21:22:24.921451	2026-04-07 21:22:24.92145	VND	\N	\N	pi_3TJaWBBINykhgxy50JPXmXoH	\N	card	stripe	pi_3TJaWBBINykhgxy50JPXmXoH	SUCCEEDED	2026-04-07 21:22:24.92145	10
11	121000.00	2026-04-07 21:50:05.954047	2026-04-07 21:50:05.955063	VND	\N	\N	pi_3TJawxBINykhgxy510XAtLP5	\N	card	stripe	pi_3TJawxBINykhgxy510XAtLP5	SUCCEEDED	2026-04-07 21:50:05.955063	11
12	121000.00	2026-04-07 21:52:35.779095	2026-04-07 21:52:35.779642	VND	\N	\N	pi_3TJazOBINykhgxy51eGlwVDV	\N	card	stripe	pi_3TJazOBINykhgxy51eGlwVDV	SUCCEEDED	2026-04-07 21:52:35.779642	12
13	4641450.00	2026-04-19 19:36:23.421412	2026-04-19 19:36:23.422409	VND	\N	\N	pi_3TNuVaBINykhgxy5039gOThm	\N	card	stripe	pi_3TNuVaBINykhgxy5039gOThm	SUCCEEDED	2026-04-19 19:36:23.422409	13
14	121000.00	2026-04-19 20:42:53.4227	2026-04-19 20:42:53.423732	VND	\N	\N	pi_3TNvcWBINykhgxy50PtiZP2f	\N	card	stripe	pi_3TNvcWBINykhgxy50PtiZP2f	SUCCEEDED	2026-04-19 20:42:53.423732	14
15	121000.00	2026-04-19 20:44:32.819403	2026-04-19 20:44:32.820909	VND	\N	\N	pi_3TNve7BINykhgxy50Mx1OxqB	\N	card	stripe	pi_3TNve7BINykhgxy50Mx1OxqB	SUCCEEDED	2026-04-19 20:44:32.820909	15
16	328900.00	2026-05-12 14:17:20.460161	2026-05-12 14:17:20.462158	VND	\N	\N	pi_3TWAWgBINykhgxy50wwpUwUV	\N	card	stripe	pi_3TWAWgBINykhgxy50wwpUwUV	SUCCEEDED	2026-05-12 14:17:20.462158	16
17	121000.00	2026-05-12 14:24:21.668843	2026-05-12 14:24:21.66935	VND	\N	\N	pi_3TWAftBINykhgxy50N05mXLu	\N	card	stripe	pi_3TWAftBINykhgxy50N05mXLu	SUCCEEDED	2026-05-12 14:24:21.66935	17
18	133344.20	2026-06-07 10:02:03.558035	2026-06-07 10:02:03.559085	VND	\N	\N	pi_3TfWy9BINykhgxy50tdDIWqq	\N	card	stripe	pi_3TfWy9BINykhgxy50tdDIWqq	SUCCEEDED	2026-06-07 10:02:03.559085	18
19	206676.80	2026-06-07 12:42:35.551997	2026-06-07 12:42:35.556058	VND	\N	\N	pi_3TfZTXBINykhgxy51iUFIA6u	\N	card	stripe	pi_3TfZTXBINykhgxy51iUFIA6u	SUCCEEDED	2026-06-07 12:42:35.556058	19
20	135300.00	2026-06-07 13:35:22.073541	2026-06-07 13:35:22.073541	VND	\N	\N	pi_3TfaIdBINykhgxy50n0AA5me	\N	card	stripe	pi_3TfaIdBINykhgxy50n0AA5me	SUCCEEDED	2026-06-07 13:35:22.073541	20
\.


--
-- Data for Name: sub_order_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sub_order_items (item_id, image_url, product_id, product_name, quantity, total_price, unit_price, variant_id, variant_name, sub_order_id) FROM stdin;
1	c0024f8e-bdc3-4797-b472-f2a450411e5d_vn-11134275-820l4-mipe3b9jyy2v73.webp	23	Gi├áy Sneaker Unisex HOKA Project Transport - ─Éen - 1162850-BYN -LS00.	1	100000.00	100000.00	44	US 8.5/9.5	1
2	98fdd789-3591-451a-b5aa-8a0a4c61a1ff_vn-11134207-7r98o-lv187gjlkws9b3.webp	14	Bß╗Ö Dß╗Ñng Cß╗Ñ Vß╗ç Sinh Laptop M├íy T├¡nh SMTech Bß╗Ö Vß╗ç Sinh B├án Ph├¡m M├án H├¼nh Tai Nghe ─Éiß╗çn Thoß║íi Nhß╗Å Gß╗ìn	1	22222.00	22222.00	11	Xanh	2
3	e558c530-6f07-4c79-8f05-5cd380447b7e_c06b51be293d745091d27f471c36ebbc.webp	15	Miß║┐ng l├│t chuß╗Öt Logitech gi├í si├¬u rß║╗ (23 x 18cm)	1	11000.00	11000.00	14	─Éen	3
4	e558c530-6f07-4c79-8f05-5cd380447b7e_c06b51be293d745091d27f471c36ebbc.webp	15	Miß║┐ng l├│t chuß╗Öt Logitech gi├í si├¬u rß║╗ (23 x 18cm)	1	11000.00	11000.00	14	─Éen	4
5	66edd73d-36f4-4944-9e18-cf7f0f879b23_vn-11134207-820l4-mifexpba18n7cd.webp	18	├üo polo Nam Regular Fit Beverly Hills Polo Club - PMRSS25TL019	1	100000.00	100000.00	20	CREAM - CR-M	5
6	c0024f8e-bdc3-4797-b472-f2a450411e5d_vn-11134275-820l4-mipe3b9jyy2v73.webp	23	Gi├áy Sneaker Unisex HOKA Project Transport - ─Éen - 1162850-BYN -LS00.	1	100000.00	100000.00	44	US 8.5/9.5	6
7	66edd73d-36f4-4944-9e18-cf7f0f879b23_vn-11134207-820l4-mifexpba18n7cd.webp	18	├üo polo Nam Regular Fit Beverly Hills Polo Club - PMRSS25TL019	1	100000.00	100000.00	20	CREAM - CR-M	7
8	9de7fba1-9141-4d03-b1bb-c8b05b81916e_vn-11134207-7r98o-lnwzok0w6igd31.webp	29	Tai nghe gaming kh├┤ng d├óy ASUS ROG CETRA TRUE Wireless, chß╗æng n╞░ß╗¢c IPX4, c├┤ng nghß╗ç chß╗æng ß╗ôn ANC	3	6000000.00	2000000.00	60	Trß║»ng	8
9	98fdd789-3591-451a-b5aa-8a0a4c61a1ff_vn-11134207-7r98o-lv187gjlkws9b3.webp	14	Bß╗Ö Dß╗Ñng Cß╗Ñ Vß╗ç Sinh Laptop M├íy T├¡nh SMTech Bß╗Ö Vß╗ç Sinh B├án Ph├¡m M├án H├¼nh Tai Nghe ─Éiß╗çn Thoß║íi Nhß╗Å Gß╗ìn	1	22222.00	22222.00	11	Xanh	9
10	e558c530-6f07-4c79-8f05-5cd380447b7e_c06b51be293d745091d27f471c36ebbc.webp	15	Miß║┐ng l├│t chuß╗Öt Logitech gi├í si├¬u rß║╗ (23 x 18cm)	1	11000.00	11000.00	14	─Éen	10
11	9de7fba1-9141-4d03-b1bb-c8b05b81916e_vn-11134207-7r98o-lnwzok0w6igd31.webp	29	Tai nghe gaming kh├┤ng d├óy ASUS ROG CETRA TRUE Wireless, chß╗æng n╞░ß╗¢c IPX4, c├┤ng nghß╗ç chß╗æng ß╗ôn ANC	1	2000000.00	2000000.00	60	Trß║»ng	11
12	e558c530-6f07-4c79-8f05-5cd380447b7e_c06b51be293d745091d27f471c36ebbc.webp	15	Miß║┐ng l├│t chuß╗Öt Logitech gi├í si├¬u rß║╗ (23 x 18cm)	1	11000.00	11000.00	14	─Éen	12
13	e558c530-6f07-4c79-8f05-5cd380447b7e_c06b51be293d745091d27f471c36ebbc.webp	15	Miß║┐ng l├│t chuß╗Öt Logitech gi├í si├¬u rß║╗ (23 x 18cm)	1	11000.00	11000.00	14	─Éen	13
14	e558c530-6f07-4c79-8f05-5cd380447b7e_c06b51be293d745091d27f471c36ebbc.webp	15	Miß║┐ng l├│t chuß╗Öt Logitech gi├í si├¬u rß║╗ (23 x 18cm)	1	11000.00	11000.00	14	─Éen	14
15	66edd73d-36f4-4944-9e18-cf7f0f879b23_vn-11134207-820l4-mifexpba18n7cd.webp	18	├üo polo Nam Regular Fit Beverly Hills Polo Club - PMRSS25TL019	1	100000.00	100000.00	20	CREAM - CR-M	15
16	9de7fba1-9141-4d03-b1bb-c8b05b81916e_vn-11134207-7r98o-lnwzok0w6igd31.webp	29	Tai nghe gaming kh├┤ng d├óy ASUS ROG CETRA TRUE Wireless, chß╗æng n╞░ß╗¢c IPX4, c├┤ng nghß╗ç chß╗æng ß╗ôn ANC	2	4000000.00	2000000.00	60	Trß║»ng	16
17	e558c530-6f07-4c79-8f05-5cd380447b7e_c06b51be293d745091d27f471c36ebbc.webp	15	Miß║┐ng l├│t chuß╗Öt Logitech gi├í si├¬u rß║╗ (23 x 18cm)	1	11000.00	11000.00	14	─Éen	17
18	e558c530-6f07-4c79-8f05-5cd380447b7e_c06b51be293d745091d27f471c36ebbc.webp	15	Miß║┐ng l├│t chuß╗Öt Logitech gi├í si├¬u rß║╗ (23 x 18cm)	1	11000.00	11000.00	14	─Éen	18
19	66edd73d-36f4-4944-9e18-cf7f0f879b23_vn-11134207-820l4-mifexpba18n7cd.webp	18	├üo polo Nam Regular Fit Beverly Hills Polo Club - PMRSS25TL019	2	200000.00	100000.00	20	CREAM - CR-M	19
20	e558c530-6f07-4c79-8f05-5cd380447b7e_c06b51be293d745091d27f471c36ebbc.webp	15	Miß║┐ng l├│t chuß╗Öt Logitech gi├í si├¬u rß║╗ (23 x 18cm)	1	11000.00	11000.00	14	─Éen	20
21	98fdd789-3591-451a-b5aa-8a0a4c61a1ff_vn-11134207-7r98o-lv187gjlkws9b3.webp	14	Bß╗Ö Dß╗Ñng Cß╗Ñ Vß╗ç Sinh Laptop M├íy T├¡nh SMTech Bß╗Ö Vß╗ç Sinh B├án Ph├¡m M├án H├¼nh Tai Nghe ─Éiß╗çn Thoß║íi Nhß╗Å Gß╗ìn	1	22222.00	22222.00	11	Xanh	21
22	98fdd789-3591-451a-b5aa-8a0a4c61a1ff_vn-11134207-7r98o-lv187gjlkws9b3.webp	14	Bß╗Ö Dß╗Ñng Cß╗Ñ Vß╗ç Sinh Laptop M├íy T├¡nh SMTech Bß╗Ö Vß╗ç Sinh B├án Ph├¡m M├án H├¼nh Tai Nghe ─Éiß╗çn Thoß║íi Nhß╗Å Gß╗ìn	4	88888.00	22222.00	11	Xanh	22
23	4b1c7fa3-7423-4932-98a8-8bc0e171e1c5_vn-11134207-7r98o-lv187gjlqj2185.webp	14	Bß╗Ö Dß╗Ñng Cß╗Ñ Vß╗ç Sinh Laptop M├íy T├¡nh SMTech Bß╗Ö Vß╗ç Sinh B├án Ph├¡m M├án H├¼nh Tai Nghe ─Éiß╗çn Thoß║íi Nhß╗Å Gß╗ìn	2	24000.00	12000.00	13	Ngß║½u Nhi├¬n	23
\.


--
-- Data for Name: sub_orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sub_orders (sub_order_id, cancelled_at, carrier, created_at, delivered_at, discount, estimated_delivery, fulfillment_status, ghn_order_code, seller_id, seller_name, shipped_at, shipping_cost, status, sub_order_number, subtotal, tax, total, tracking_number, tracking_url, updated_at, group_id) FROM stdin;
1	\N	\N	2026-03-27 11:34:28.584278	\N	0.00	\N	\N	\N	106	Seller 106	\N	99000.00	PENDING	OG-1774586068558-057C8650-S106	100000.00	19900.00	218900.00	\N	\N	2026-03-27 11:34:28.584278	1
2	\N	\N	2026-03-27 11:48:35.333578	2026-03-27 11:49:22.300676	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1774586915311-3E6A005C-S102	22222.00	12122.20	133344.20	\N	\N	2026-03-27 11:49:22.310682	2
3	\N	\N	2026-03-29 12:28:25.52556	2026-03-29 12:28:54.225033	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1774762105518-5A777F80-S102	11000.00	11000.00	121000.00	\N	\N	2026-03-29 12:28:54.23009	3
4	\N	\N	2026-03-29 14:41:27.148487	\N	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	PENDING	OG-1774770087141-76440FF2-S102	11000.00	11000.00	121000.00	\N	\N	2026-03-29 14:41:27.148487	4
5	\N	\N	2026-03-31 17:54:42.650425	\N	0.00	\N	\N	\N	105	Seller 105	\N	49500.00	PENDING	OG-1774954482638-08CA053B-S105	100000.00	14950.00	164450.00	\N	\N	2026-03-31 17:54:42.650425	5
6	\N	\N	2026-03-31 17:54:42.659931	\N	0.00	\N	\N	\N	106	Seller 106	\N	49500.00	PENDING	OG-1774954482638-08CA053B-S106	100000.00	14950.00	164450.00	\N	\N	2026-03-31 17:54:42.659931	5
7	\N	\N	2026-04-02 18:23:11.397845	\N	0.00	\N	\N	\N	105	Seller 105	\N	64750.00	PENDING	OG-1775128991384-CD122001-S105	100000.00	16475.00	181225.00	\N	\N	2026-04-02 18:23:11.397845	6
8	\N	\N	2026-04-02 18:23:11.407147	\N	0.00	\N	\N	\N	108	Seller 108	\N	64750.00	PENDING	OG-1775128991384-CD122001-S108	6000000.00	606475.00	6671225.00	\N	\N	2026-04-02 18:23:11.407147	6
9	\N	\N	2026-04-07 20:24:04.322456	2026-04-07 20:24:44.589648	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1775568244311-E2364838-S102	22222.00	12122.20	133344.20	\N	\N	2026-04-07 20:24:44.595147	7
10	\N	\N	2026-04-07 20:26:06.698272	2026-04-07 20:26:28.288554	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1775568366695-22618DE0-S102	11000.00	11000.00	121000.00	\N	\N	2026-04-07 20:26:28.292014	8
11	\N	\N	2026-04-07 21:21:56.489979	\N	0.00	\N	\N	\N	108	Seller 108	\N	109000.00	PENDING	OG-1775571716481-DC59A963-S108	2000000.00	210900.00	2319900.00	\N	\N	2026-04-07 21:21:56.489979	9
12	\N	\N	2026-04-07 21:22:24.908037	2026-04-07 21:22:39.360112	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1775571744905-3A6728F5-S102	11000.00	11000.00	121000.00	\N	\N	2026-04-07 21:22:39.366258	10
13	\N	\N	2026-04-07 21:50:05.897216	2026-04-07 21:50:35.308429	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1775573405891-93285231-S102	11000.00	11000.00	121000.00	\N	\N	2026-04-07 21:50:35.31585	11
14	\N	\N	2026-04-07 21:52:35.751382	2026-04-07 21:53:08.0072	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1775573555745-62BC5EB6-S102	11000.00	11000.00	121000.00	\N	\N	2026-04-07 21:53:08.013189	12
15	\N	\N	2026-04-19 19:36:23.354384	\N	0.00	\N	\N	\N	105	Seller 105	\N	59750.00	PENDING	OG-1776602183347-C19F62CB-S105	100000.00	15975.00	175725.00	\N	\N	2026-04-19 19:36:23.354384	13
16	\N	\N	2026-04-19 19:36:23.363526	\N	0.00	\N	\N	\N	108	Seller 108	\N	59750.00	PENDING	OG-1776602183347-C19F62CB-S108	4000000.00	405975.00	4465725.00	\N	\N	2026-04-19 19:36:23.363526	13
17	\N	\N	2026-04-19 20:42:53.364617	2026-04-19 20:43:21.403009	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1776606173358-DA601969-S102	11000.00	11000.00	121000.00	\N	\N	2026-04-19 20:43:21.409336	14
18	\N	\N	2026-04-19 20:44:32.807296	2026-04-19 20:44:50.721548	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1776606272804-2C433603-S102	11000.00	11000.00	121000.00	\N	\N	2026-04-19 20:44:50.727119	15
19	\N	\N	2026-05-12 14:17:20.376094	\N	0.00	\N	\N	\N	105	Seller 105	\N	99000.00	PENDING	OG-1778570240366-1C320818-S105	200000.00	29900.00	328900.00	\N	\N	2026-05-12 14:17:20.376094	16
20	\N	\N	2026-05-12 14:24:21.648245	2026-05-12 14:33:58.187447	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1778570661645-9F7143E6-S102	11000.00	11000.00	121000.00	\N	\N	2026-05-12 14:33:58.190681	17
21	\N	\N	2026-06-07 10:02:03.502549	2026-06-07 10:02:49.878308	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1780801323495-E7662050-S102	22222.00	12122.20	133344.20	\N	\N	2026-06-07 10:02:49.884403	18
22	\N	\N	2026-06-07 12:42:35.523029	2026-06-07 13:08:50.421906	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1780810955512-76E99340-S102	88888.00	18788.80	206676.80	\N	\N	2026-06-07 13:08:50.425848	19
23	\N	\N	2026-06-07 13:35:22.059962	2026-06-07 13:36:39.783002	0.00	\N	\N	\N	102	Seller 102	\N	99000.00	DELIVERED	OG-1780814122056-EEB7A3D7-S102	24000.00	12300.00	135300.00	\N	\N	2026-06-07 13:36:39.787812	20
\.


--
-- Name: cart_items_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cart_items_item_id_seq', 35, true);


--
-- Name: carts_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.carts_cart_id_seq', 10, true);


--
-- Name: order_groups_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_groups_group_id_seq', 20, true);


--
-- Name: payment_transactions_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.payment_transactions_transaction_id_seq', 20, true);


--
-- Name: sub_order_items_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sub_order_items_item_id_seq', 23, true);


--
-- Name: sub_orders_sub_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sub_orders_sub_order_id_seq', 23, true);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (item_id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (cart_id);


--
-- Name: order_groups order_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_groups
    ADD CONSTRAINT order_groups_pkey PRIMARY KEY (group_id);


--
-- Name: payment_transactions payment_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT payment_transactions_pkey PRIMARY KEY (transaction_id);


--
-- Name: sub_order_items sub_order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sub_order_items
    ADD CONSTRAINT sub_order_items_pkey PRIMARY KEY (item_id);


--
-- Name: sub_orders sub_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sub_orders
    ADD CONSTRAINT sub_orders_pkey PRIMARY KEY (sub_order_id);


--
-- Name: order_groups uk11h1w6usmwikh6t759mqhbhj8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_groups
    ADD CONSTRAINT uk11h1w6usmwikh6t759mqhbhj8 UNIQUE (group_number);


--
-- Name: sub_orders uk1lmiax0oo7xx3iqet7jajspwt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sub_orders
    ADD CONSTRAINT uk1lmiax0oo7xx3iqet7jajspwt UNIQUE (sub_order_number);


--
-- Name: carts uk64t7ox312pqal3p7fg9o503c2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id);


--
-- Name: cart_items ukia0vdyyx8cilyaysrssqqj0bp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT ukia0vdyyx8cilyaysrssqqj0bp UNIQUE (cart_id, product_id, variant_id);


--
-- Name: payment_transactions ukohtafpfcbxdd1lweogsh93jd1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT ukohtafpfcbxdd1lweogsh93jd1 UNIQUE (idempotency_key);


--
-- Name: sub_order_items fk5v0m24lqb26wr46210sdxhduu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sub_order_items
    ADD CONSTRAINT fk5v0m24lqb26wr46210sdxhduu FOREIGN KEY (sub_order_id) REFERENCES public.sub_orders(sub_order_id);


--
-- Name: sub_orders fk8noullt4k2ydiwck3ivi0jxi3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sub_orders
    ADD CONSTRAINT fk8noullt4k2ydiwck3ivi0jxi3 FOREIGN KEY (group_id) REFERENCES public.order_groups(group_id);


--
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(cart_id);


--
-- Name: payment_transactions fkspqd5e2tfb9aoj9l4a02ruq7h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT fkspqd5e2tfb9aoj9l4a02ruq7h FOREIGN KEY (group_id) REFERENCES public.order_groups(group_id);


--
-- PostgreSQL database dump complete
--

\unrestrict aPizkY4O3qG8a8D7l4jF3vejqbJe8AXAva4IFoZyvAPLHiy8kMHtoIU63t8EhD1

