--
-- PostgreSQL database dump
--

\restrict XyBC3xHUqAdK2bc5SiZJxCSdoJexSnTEG1JVUbePV0RzqgqQ4AZFG6U6ZWTSz9a

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg12+1)
-- Dumped by pg_dump version 17.7 (Debian 17.7-3.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.voucher_usages DROP CONSTRAINT IF EXISTS fkguvf95urdn2namu0hgiasgttx;
ALTER TABLE IF EXISTS ONLY public.voucher_scopes DROP CONSTRAINT IF EXISTS fkg2w80va912yy28bjvyfd1t30o;
DROP INDEX IF EXISTS public.idx_voucher_usage_voucher;
DROP INDEX IF EXISTS public.idx_voucher_usage_user;
DROP INDEX IF EXISTS public.idx_voucher_usage_order;
DROP INDEX IF EXISTS public.idx_voucher_time_range;
DROP INDEX IF EXISTS public.idx_voucher_status;
DROP INDEX IF EXISTS public.idx_voucher_scope_voucher;
DROP INDEX IF EXISTS public.idx_voucher_scope_target;
DROP INDEX IF EXISTS public.idx_voucher_code;
DROP INDEX IF EXISTS public.idx_voucher_category;
DROP INDEX IF EXISTS public.idx_voucher_apply_mode;
DROP INDEX IF EXISTS public.idx_discount_history_variant;
DROP INDEX IF EXISTS public.idx_discount_history_product;
DROP INDEX IF EXISTS public.idx_discount_history_percent;
DROP INDEX IF EXISTS public.idx_discount_history_dates;
ALTER TABLE IF EXISTS ONLY public.vouchers DROP CONSTRAINT IF EXISTS vouchers_pkey;
ALTER TABLE IF EXISTS ONLY public.voucher_usages DROP CONSTRAINT IF EXISTS voucher_usages_pkey;
ALTER TABLE IF EXISTS ONLY public.voucher_scopes DROP CONSTRAINT IF EXISTS voucher_scopes_pkey;
ALTER TABLE IF EXISTS ONLY public.voucher_usages DROP CONSTRAINT IF EXISTS uk_voucher_order;
ALTER TABLE IF EXISTS ONLY public.vouchers DROP CONSTRAINT IF EXISTS uk30ftp2biebbvpik8e49wlmady;
ALTER TABLE IF EXISTS ONLY public.product_discount_history DROP CONSTRAINT IF EXISTS product_discount_history_pkey;
DROP TABLE IF EXISTS public.vouchers;
DROP TABLE IF EXISTS public.voucher_usages;
DROP TABLE IF EXISTS public.voucher_scopes;
DROP TABLE IF EXISTS public.product_discount_history;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product_discount_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_discount_history (
    id bigint NOT NULL,
    discount_name character varying(255) NOT NULL,
    discount_percent integer NOT NULL,
    discounted_price numeric(12,2) NOT NULL,
    end_time timestamp(6) without time zone NOT NULL,
    original_price numeric(12,2) NOT NULL,
    product_id bigint NOT NULL,
    recorded_at timestamp(6) without time zone NOT NULL,
    sale_campaign_id bigint,
    start_time timestamp(6) without time zone NOT NULL,
    variant_id bigint,
    voucher_id bigint
);


--
-- Name: product_discount_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_discount_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_discount_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voucher_scopes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voucher_scopes (
    id bigint NOT NULL,
    scope_type character varying(20) NOT NULL,
    target_id bigint,
    voucher_id bigint NOT NULL,
    CONSTRAINT voucher_scopes_scope_type_check CHECK (((scope_type)::text = ANY ((ARRAY['ALL'::character varying, 'PRODUCT'::character varying, 'VARIANT'::character varying, 'CATEGORY'::character varying])::text[])))
);


--
-- Name: voucher_scopes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.voucher_scopes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voucher_scopes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voucher_usages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.voucher_usages (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    used_at timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    voucher_id bigint NOT NULL
);


--
-- Name: voucher_usages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.voucher_usages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voucher_usages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vouchers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vouchers (
    id bigint NOT NULL,
    apply_mode character varying(20) NOT NULL,
    category character varying(20) NOT NULL,
    code character varying(50),
    created_at timestamp(6) without time zone,
    current_usage_count integer,
    description text,
    discount_value numeric(12,2) NOT NULL,
    end_time timestamp(6) without time zone NOT NULL,
    max_discount_amount numeric(12,2),
    min_order_amount numeric(12,2),
    name character varying(255) NOT NULL,
    sale_campaign_id bigint,
    start_time timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    type character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    usage_limit integer,
    usage_limit_per_user integer,
    CONSTRAINT vouchers_apply_mode_check CHECK (((apply_mode)::text = ANY ((ARRAY['AUTO'::character varying, 'CODE_REQUIRED'::character varying])::text[]))),
    CONSTRAINT vouchers_category_check CHECK (((category)::text = ANY ((ARRAY['PRODUCT'::character varying, 'SHIPPING'::character varying])::text[]))),
    CONSTRAINT vouchers_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SCHEDULED'::character varying, 'ACTIVE'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT vouchers_type_check CHECK (((type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FIXED_AMOUNT'::character varying])::text[])))
);


--
-- Name: vouchers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vouchers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vouchers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: product_discount_history; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_discount_history (id, discount_name, discount_percent, discounted_price, end_time, original_price, product_id, recorded_at, sale_campaign_id, start_time, variant_id, voucher_id) FROM stdin;
1	Giß║úm gi├í h├¿ 2026	20	10232000.00	2026-04-21 03:05:00	12790000.00	2	2026-03-21 10:05:42.68383	2	2026-03-21 03:06:00	4	\N
2	Giß║úm gi├í h├¿ 2026	20	10232000.00	2026-04-21 03:05:00	12790000.00	2	2026-03-21 10:05:42.693498	2	2026-03-21 03:06:00	3	\N
3	Giß║úm gi├í h├¿ 2026	20	10232000.00	2026-04-21 03:05:00	12790000.00	2	2026-03-21 10:05:42.695814	2	2026-03-21 03:06:00	5	\N
4	Giß║úm gi├í h├¿ 2026	20	28552000.00	2026-04-21 03:05:00	35690000.00	1	2026-03-21 10:05:42.699596	2	2026-03-21 03:06:00	2	\N
5	Giß║úm gi├í h├¿ 2026	20	28552000.00	2026-04-21 03:05:00	35690000.00	1	2026-03-21 10:05:42.702389	2	2026-03-21 03:06:00	1	\N
6	Giß║úm gi├í h├¿ 2026	20	30799200.00	2026-04-21 03:05:00	38499000.00	3	2026-03-21 10:05:42.706335	2	2026-03-21 03:06:00	7	\N
7	Giß║úm gi├í h├¿ 2026	20	30799200.00	2026-04-21 03:05:00	38499000.00	3	2026-03-21 10:05:42.709627	2	2026-03-21 03:06:00	6	\N
8	Giß║úm gi├í h├¿ 26	10	11511000.00	2026-07-21 03:20:00	12790000.00	2	2026-03-21 10:20:47.660884	4	2026-03-21 03:21:00	4	\N
9	Giß║úm gi├í h├¿ 26	10	11511000.00	2026-07-21 03:20:00	12790000.00	2	2026-03-21 10:20:47.666314	4	2026-03-21 03:21:00	3	\N
10	Giß║úm gi├í h├¿ 26	10	11511000.00	2026-07-21 03:20:00	12790000.00	2	2026-03-21 10:20:47.669099	4	2026-03-21 03:21:00	5	\N
11	Giß║úm gi├í h├¿ 26	10	32121000.00	2026-07-21 03:20:00	35690000.00	1	2026-03-21 10:20:47.672456	4	2026-03-21 03:21:00	2	\N
12	Giß║úm gi├í h├¿ 26	10	32121000.00	2026-07-21 03:20:00	35690000.00	1	2026-03-21 10:20:47.675189	4	2026-03-21 03:21:00	1	\N
13	Giß║úm gi├í h├¿ 26	10	34649100.00	2026-07-21 03:20:00	38499000.00	3	2026-03-21 10:20:47.678808	4	2026-03-21 03:21:00	7	\N
14	Giß║úm gi├í h├¿ 26	10	34649100.00	2026-07-21 03:20:00	38499000.00	3	2026-03-21 10:20:47.681975	4	2026-03-21 03:21:00	6	\N
15	Black Fridayyyyyyyyyyy	20	960000.00	2026-07-04 06:14:00	1200000.00	30	2026-06-07 13:15:05.938047	5	2026-06-08 06:14:00	61	\N
16	Black Fridayyyyyyyyyyy	20	8000000.00	2026-07-04 06:14:00	10000000.00	31	2026-06-07 13:15:05.950036	5	2026-06-08 06:14:00	62	\N
17	Black Fridayyyyyyyyyyy	20	8000000.00	2026-07-04 06:14:00	10000000.00	31	2026-06-07 13:15:05.954485	5	2026-06-08 06:14:00	63	\N
18	Black Fridayggfdgdgdg	20	960000.00	2026-06-26 06:43:00	1200000.00	30	2026-06-07 13:43:56.281629	6	2026-06-07 06:46:00	61	\N
\.


--
-- Data for Name: voucher_scopes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.voucher_scopes (id, scope_type, target_id, voucher_id) FROM stdin;
1	VARIANT	4	2
2	VARIANT	3	2
3	VARIANT	5	2
4	VARIANT	2	2
5	VARIANT	1	2
6	VARIANT	7	2
7	VARIANT	6	2
8	VARIANT	4	3
9	VARIANT	3	3
10	VARIANT	5	3
11	VARIANT	2	3
12	VARIANT	1	3
13	VARIANT	7	3
14	VARIANT	6	3
15	VARIANT	61	6
16	VARIANT	62	6
17	VARIANT	63	6
18	VARIANT	61	8
\.


--
-- Data for Name: voucher_usages; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.voucher_usages (id, order_id, used_at, user_id, voucher_id) FROM stdin;
\.


--
-- Data for Name: vouchers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vouchers (id, apply_mode, category, code, created_at, current_usage_count, description, discount_value, end_time, max_discount_amount, min_order_amount, name, sale_campaign_id, start_time, status, type, updated_at, usage_limit, usage_limit_per_user) FROM stdin;
1	AUTO	PRODUCT	\N	2026-03-21 10:03:40.45938	0	Auto-generated from sale campaign: Summer Sale 2026	0.00	2026-04-30 23:59:59	\N	\N	Summer Sale 2026	1	2026-03-21 00:00:00	ACTIVE	PERCENTAGE	2026-03-21 10:03:40.45938	\N	\N
2	AUTO	PRODUCT	\N	2026-03-21 10:05:42.713558	0	Auto-generated from sale campaign: Giß║úm gi├í h├¿ 2026	20.00	2026-04-21 03:05:00	\N	\N	Giß║úm gi├í h├¿ 2026	2	2026-03-21 03:06:00	ACTIVE	PERCENTAGE	2026-03-21 10:05:42.713558	\N	\N
3	AUTO	PRODUCT	\N	2026-03-21 10:20:47.68647	0	Auto-generated from sale campaign: Giß║úm gi├í h├¿ 26	10.00	2026-07-21 03:20:00	\N	\N	Giß║úm gi├í h├¿ 26	4	2026-03-21 03:21:00	ACTIVE	PERCENTAGE	2026-03-21 10:20:47.68647	\N	\N
4	CODE_REQUIRED	PRODUCT	WELCOME20	2026-04-08 16:13:05.013805	0	asdasdasdasdasdassd	50.00	2026-05-01 02:10:00	999999.00	0.00	M├áu Sß║»c	\N	2026-04-08 02:10:00	ACTIVE	PERCENTAGE	2026-04-08 16:13:12.257942	10	10000000
5	AUTO	PRODUCT	\N	2026-06-07 13:14:04.612864	0	\N	10.00	2026-07-31 23:13:00	999999.00	10000.00	Black Fridayyyyy	\N	2026-06-06 23:13:00	ACTIVE	PERCENTAGE	2026-06-07 13:14:08.336722	11	1
6	AUTO	PRODUCT	\N	2026-06-07 13:15:05.96059	0	Auto-generated from sale campaign: Black Fridayyyyyyyyyyy	20.00	2026-07-04 06:14:00	\N	\N	Black Fridayyyyyyyyyyy	5	2026-06-08 06:14:00	SCHEDULED	PERCENTAGE	2026-06-07 13:15:05.96059	\N	\N
7	CODE_REQUIRED	PRODUCT	WECLOME22222	2026-06-07 13:43:06.106326	0	\N	10.00	2026-06-19 23:42:00	70000000.00	10000.00	M├áu Sß║»c	\N	2026-06-06 23:42:00	ACTIVE	PERCENTAGE	2026-06-07 13:43:10.039746	11111111	1
8	AUTO	PRODUCT	\N	2026-06-07 13:43:56.284987	0	Auto-generated from sale campaign: Black Fridayggfdgdgdg	20.00	2026-06-26 06:43:00	\N	\N	Black Fridayggfdgdgdg	6	2026-06-07 06:46:00	ACTIVE	PERCENTAGE	2026-06-07 13:43:56.284987	\N	\N
\.


--
-- Name: product_discount_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_discount_history_id_seq', 18, true);


--
-- Name: voucher_scopes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.voucher_scopes_id_seq', 18, true);


--
-- Name: voucher_usages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.voucher_usages_id_seq', 1, false);


--
-- Name: vouchers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vouchers_id_seq', 8, true);


--
-- Name: product_discount_history product_discount_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_discount_history
    ADD CONSTRAINT product_discount_history_pkey PRIMARY KEY (id);


--
-- Name: vouchers uk30ftp2biebbvpik8e49wlmady; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT uk30ftp2biebbvpik8e49wlmady UNIQUE (code);


--
-- Name: voucher_usages uk_voucher_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voucher_usages
    ADD CONSTRAINT uk_voucher_order UNIQUE (voucher_id, order_id);


--
-- Name: voucher_scopes voucher_scopes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voucher_scopes
    ADD CONSTRAINT voucher_scopes_pkey PRIMARY KEY (id);


--
-- Name: voucher_usages voucher_usages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voucher_usages
    ADD CONSTRAINT voucher_usages_pkey PRIMARY KEY (id);


--
-- Name: vouchers vouchers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT vouchers_pkey PRIMARY KEY (id);


--
-- Name: idx_discount_history_dates; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_discount_history_dates ON public.product_discount_history USING btree (start_time, end_time);


--
-- Name: idx_discount_history_percent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_discount_history_percent ON public.product_discount_history USING btree (discount_percent);


--
-- Name: idx_discount_history_product; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_discount_history_product ON public.product_discount_history USING btree (product_id);


--
-- Name: idx_discount_history_variant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_discount_history_variant ON public.product_discount_history USING btree (variant_id);


--
-- Name: idx_voucher_apply_mode; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_apply_mode ON public.vouchers USING btree (apply_mode);


--
-- Name: idx_voucher_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_category ON public.vouchers USING btree (category);


--
-- Name: idx_voucher_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_code ON public.vouchers USING btree (code);


--
-- Name: idx_voucher_scope_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_scope_target ON public.voucher_scopes USING btree (scope_type, target_id);


--
-- Name: idx_voucher_scope_voucher; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_scope_voucher ON public.voucher_scopes USING btree (voucher_id);


--
-- Name: idx_voucher_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_status ON public.vouchers USING btree (status);


--
-- Name: idx_voucher_time_range; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_time_range ON public.vouchers USING btree (start_time, end_time);


--
-- Name: idx_voucher_usage_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_usage_order ON public.voucher_usages USING btree (order_id);


--
-- Name: idx_voucher_usage_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_usage_user ON public.voucher_usages USING btree (user_id);


--
-- Name: idx_voucher_usage_voucher; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_voucher_usage_voucher ON public.voucher_usages USING btree (voucher_id);


--
-- Name: voucher_scopes fkg2w80va912yy28bjvyfd1t30o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voucher_scopes
    ADD CONSTRAINT fkg2w80va912yy28bjvyfd1t30o FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);


--
-- Name: voucher_usages fkguvf95urdn2namu0hgiasgttx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.voucher_usages
    ADD CONSTRAINT fkguvf95urdn2namu0hgiasgttx FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);


--
-- PostgreSQL database dump complete
--

\unrestrict XyBC3xHUqAdK2bc5SiZJxCSdoJexSnTEG1JVUbePV0RzqgqQ4AZFG6U6ZWTSz9a

