--
-- PostgreSQL database dump
--

\restrict IZXZWCYm3UXp2rbYVbtKZyhN04INOZQ01dRA4NdNmQWqh0mi8oZIKZYoPWXdUVm

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg12+1)
-- Dumped by pg_dump version 17.7 (Debian 17.7-3.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.reviews DROP CONSTRAINT IF EXISTS ukr8vcm6neix10qorxt37o37kd8;
ALTER TABLE IF EXISTS ONLY public.reviews DROP CONSTRAINT IF EXISTS uk_review_user_product_order;
ALTER TABLE IF EXISTS ONLY public.reviews DROP CONSTRAINT IF EXISTS reviews_pkey;
DROP TABLE IF EXISTS public.reviews;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    comment text,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    helpful_count integer,
    images jsonb,
    not_helpful_count integer,
    order_id bigint,
    product_id bigint NOT NULL,
    rating integer NOT NULL,
    sentiment character varying(20) NOT NULL,
    sentiment_score double precision,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reviews (id, comment, created_at, email, helpful_count, images, not_helpful_count, order_id, product_id, rating, sentiment, sentiment_score, updated_at, user_id) FROM stdin;
1	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:10.45374	user36@ecom.com	24	[]	7	78	34	5	POSITIVE	\N	2026-03-23 06:55:10.45374	36
2	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:10.557874	user69@ecom.com	27	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	2	56	47	4	POSITIVE	\N	2026-03-23 06:55:10.557874	69
3	Ea odit earum labore sit molestiae ut fugit sed rerum sed tempora quasi fugiat ab est.	2026-03-23 06:55:10.566761	user47@ecom.com	49	[]	10	49	135	5	POSITIVE	\N	2026-03-23 06:55:10.566761	47
4	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:10.572138	user30@ecom.com	32	[]	2	36	77	5	POSITIVE	\N	2026-03-23 06:55:10.572138	30
5	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.575868	user10@ecom.com	20	["1.png", "2.png", "3.png"]	1	75	77	5	POSITIVE	\N	2026-03-23 06:55:10.575868	10
6	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:10.582516	user87@ecom.com	27	[]	6	59	21	5	POSITIVE	\N	2026-03-23 06:55:10.582516	87
7	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:10.589014	user86@ecom.com	47	[]	0	32	77	4	POSITIVE	\N	2026-03-23 06:55:10.589014	86
8	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.594014	user44@ecom.com	36	[]	10	51	134	4	POSITIVE	\N	2026-03-23 06:55:10.594014	44
9	Decent product for the price. Does the job but could be better. Shipping was a bit slow.	2026-03-23 06:55:10.601212	user98@ecom.com	4	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	7	36	3	3	NEUTRAL	\N	2026-03-23 06:55:10.601212	98
10	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:10.609149	user57@ecom.com	12	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	8	79	117	5	POSITIVE	\N	2026-03-23 06:55:10.609149	57
11	Nisi explicabo sunt modi odio dolorem ad non aspernatur molestias exercitationem rerum repellat velit iure recusandae qui facere doloribus.	2026-03-23 06:55:10.617581	user43@ecom.com	17	[]	8	8	13	5	POSITIVE	\N	2026-03-23 06:55:10.617581	43
12	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:10.626551	user40@ecom.com	36	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	11	11	33	5	POSITIVE	\N	2026-03-23 06:55:10.626551	40
13	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:10.633806	user48@ecom.com	22	[]	9	8	17	5	POSITIVE	\N	2026-03-23 06:55:10.633806	48
14	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:10.638827	user7@ecom.com	19	[]	4	73	142	4	POSITIVE	\N	2026-03-23 06:55:10.638827	7
15	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:10.654137	user33@ecom.com	14	[]	5	25	90	4	POSITIVE	\N	2026-03-23 06:55:10.654137	33
16	It's fine. Not the best quality but not terrible either. You get what you pay for.	2026-03-23 06:55:10.660056	user45@ecom.com	35	[]	1	24	116	3	NEUTRAL	\N	2026-03-23 06:55:10.660056	45
17	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.664853	user59@ecom.com	30	[]	7	77	142	5	POSITIVE	\N	2026-03-23 06:55:10.664853	59
18	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:10.669138	user17@ecom.com	13	[]	10	85	120	4	POSITIVE	\N	2026-03-23 06:55:10.669138	17
19	Quia voluptas labore odit ut iusto qui doloribus saepe vero enim consequuntur occaecati quia beatae cum impedit.	2026-03-23 06:55:10.673534	user87@ecom.com	6	[]	3	81	5	4	POSITIVE	\N	2026-03-23 06:55:10.674106	87
20	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:10.678864	user59@ecom.com	29	[]	7	83	118	5	POSITIVE	\N	2026-03-23 06:55:10.678864	59
21	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:10.683271	user37@ecom.com	46	[]	11	8	116	4	POSITIVE	\N	2026-03-23 06:55:10.683271	37
22	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:10.689174	user85@ecom.com	44	[]	2	20	19	4	POSITIVE	\N	2026-03-23 06:55:10.689174	85
23	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.693616	user39@ecom.com	26	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	2	41	24	5	POSITIVE	\N	2026-03-23 06:55:10.693616	39
24	Repellendus veniam unde earum expedita vel ad molestiae officiis saepe velit enim.	2026-03-23 06:55:10.698274	user61@ecom.com	46	[]	10	3	89	3	NEUTRAL	\N	2026-03-23 06:55:10.698274	61
25	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:10.703185	user41@ecom.com	34	[]	2	75	78	5	POSITIVE	\N	2026-03-23 06:55:10.703185	41
26	Decent product for the price. Does the job but could be better. Shipping was a bit slow.	2026-03-23 06:55:10.711084	user74@ecom.com	35	[]	10	48	38	3	NEUTRAL	\N	2026-03-23 06:55:10.711084	74
27	The product is okay, but nothing special. It works as advertised but I expected a bit more quality.	2026-03-23 06:55:10.716101	user9@ecom.com	37	[]	6	31	110	3	NEUTRAL	\N	2026-03-23 06:55:10.716101	9
28	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:10.726015	user65@ecom.com	18	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	1	18	140	5	POSITIVE	\N	2026-03-23 06:55:10.726015	65
29	Decent product for the price. Does the job but could be better. Shipping was a bit slow.	2026-03-23 06:55:10.734645	user15@ecom.com	38	[]	2	17	107	3	NEUTRAL	\N	2026-03-23 06:55:10.734645	15
30	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:10.739832	user58@ecom.com	15	[]	5	73	52	5	POSITIVE	\N	2026-03-23 06:55:10.739832	58
31	Labore voluptate eligendi vel labore architecto ipsa non necessitatibus ut voluptatem et aut non accusamus est quia.	2026-03-23 06:55:10.744157	user73@ecom.com	44	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	3	99	92	5	POSITIVE	\N	2026-03-23 06:55:10.744157	73
32	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:10.750958	user23@ecom.com	36	[]	5	14	106	5	POSITIVE	\N	2026-03-23 06:55:10.750958	23
33	Eum odit ullam voluptatem eos consequatur reprehenderit est sit nisi placeat tempora.	2026-03-23 06:55:10.756396	user26@ecom.com	29	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	3	13	87	3	NEUTRAL	\N	2026-03-23 06:55:10.756396	26
34	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.762748	user30@ecom.com	23	[]	9	33	138	5	POSITIVE	\N	2026-03-23 06:55:10.762748	30
35	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.769626	user67@ecom.com	22	[]	7	26	92	5	POSITIVE	\N	2026-03-23 06:55:10.769626	67
36	The product is okay, but nothing special. It works as advertised but I expected a bit more quality.	2026-03-23 06:55:10.774087	user82@ecom.com	44	[]	5	13	36	3	NEUTRAL	\N	2026-03-23 06:55:10.774087	82
37	Average product. Works as expected but nothing impressive. Might look for alternatives next time.	2026-03-23 06:55:10.778467	user72@ecom.com	33	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	7	15	75	3	NEUTRAL	\N	2026-03-23 06:55:10.778467	72
38	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:10.78297	user28@ecom.com	4	[]	7	38	122	4	POSITIVE	\N	2026-03-23 06:55:10.78297	28
39	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:10.787974	user3@ecom.com	8	[]	10	77	80	5	POSITIVE	\N	2026-03-23 06:55:10.787974	3
40	Average product. Works as expected but nothing impressive. Might look for alternatives next time.	2026-03-23 06:55:10.792039	user20@ecom.com	16	["1.png", "2.png", "3.png"]	6	23	128	3	NEUTRAL	\N	2026-03-23 06:55:10.792039	20
41	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:10.797223	user82@ecom.com	12	["1.png", "2.png", "3.png"]	6	99	74	4	POSITIVE	\N	2026-03-23 06:55:10.797223	82
42	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.804532	user53@ecom.com	30	["1.png", "2.png", "3.png"]	8	56	89	4	POSITIVE	\N	2026-03-23 06:55:10.804532	53
43	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:10.811811	user59@ecom.com	36	[]	1	33	125	5	POSITIVE	\N	2026-03-23 06:55:10.811811	59
44	Voluptatum dolores nemo dolorem accusamus beatae asperiores voluptatum a distinctio excepturi earum temporibus aut sed.	2026-03-23 06:55:10.816103	user81@ecom.com	46	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	1	86	12	4	POSITIVE	\N	2026-03-23 06:55:10.816103	81
45	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.820343	user10@ecom.com	26	[]	3	6	22	4	POSITIVE	\N	2026-03-23 06:55:10.820876	10
46	Nostrum provident adipisci commodi possimus iure odio non quibusdam amet similique accusantium iure voluptate aut ut minus voluptas doloribus.	2026-03-23 06:55:10.824869	user46@ecom.com	41	["1.png", "2.png", "3.png"]	6	6	26	5	POSITIVE	\N	2026-03-23 06:55:10.824869	46
47	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:10.829659	user69@ecom.com	31	[]	5	23	27	4	POSITIVE	\N	2026-03-23 06:55:10.829659	69
48	Animi qui aut dolor omnis enim est ipsa deserunt quibusdam cumque optio enim est error consequuntur voluptatibus asperiores nesciunt sit.	2026-03-23 06:55:10.833959	user23@ecom.com	2	[]	5	10	70	5	POSITIVE	\N	2026-03-23 06:55:10.833959	23
49	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:10.83811	user67@ecom.com	16	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	7	83	56	4	POSITIVE	\N	2026-03-23 06:55:10.83811	67
50	Fugit similique omnis et sit dolorem optio aut libero natus sit et quisquam ut qui enim.	2026-03-23 06:55:10.843167	user59@ecom.com	8	[]	4	17	55	3	NEUTRAL	\N	2026-03-23 06:55:10.843167	59
51	Eum pariatur aut modi ipsam laudantium velit minus architecto et quia id ratione rem voluptatem est eos eaque magni.	2026-03-23 06:55:10.847975	user71@ecom.com	3	[]	5	70	27	5	POSITIVE	\N	2026-03-23 06:55:10.847975	71
52	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:10.852861	user48@ecom.com	35	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	3	13	3	5	POSITIVE	\N	2026-03-23 06:55:10.852861	48
53	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:10.857628	user17@ecom.com	18	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	7	6	135	5	POSITIVE	\N	2026-03-23 06:55:10.857628	17
54	Decent product for the price. Does the job but could be better. Shipping was a bit slow.	2026-03-23 06:55:10.861952	user21@ecom.com	42	[]	5	51	133	3	NEUTRAL	\N	2026-03-23 06:55:10.861952	21
55	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:10.865714	user92@ecom.com	16	[]	1	24	68	5	POSITIVE	\N	2026-03-23 06:55:10.865714	92
56	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:10.870039	user72@ecom.com	46	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	7	49	133	4	POSITIVE	\N	2026-03-23 06:55:10.870039	72
57	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:10.874969	user78@ecom.com	13	[]	2	11	98	5	POSITIVE	\N	2026-03-23 06:55:10.874969	78
58	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:10.897187	user18@ecom.com	33	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	2	97	32	5	POSITIVE	\N	2026-03-23 06:55:10.897187	18
59	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:10.910528	user25@ecom.com	21	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	11	38	128	5	POSITIVE	\N	2026-03-23 06:55:10.910528	25
60	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:10.920548	user48@ecom.com	8	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	1	41	112	5	POSITIVE	\N	2026-03-23 06:55:10.920548	48
61	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:10.925518	user67@ecom.com	24	[]	7	13	104	5	POSITIVE	\N	2026-03-23 06:55:10.925518	67
62	Quia et iste quis culpa accusamus et quibusdam vel saepe libero odit repellendus eligendi iusto repellat eligendi et praesentium.	2026-03-23 06:55:10.929949	user16@ecom.com	33	[]	8	16	72	5	POSITIVE	\N	2026-03-23 06:55:10.929949	16
63	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:10.953543	user26@ecom.com	26	[]	7	63	89	5	POSITIVE	\N	2026-03-23 06:55:10.953543	26
64	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.960806	user67@ecom.com	23	[]	6	94	35	5	POSITIVE	\N	2026-03-23 06:55:10.960806	67
65	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:10.965742	user94@ecom.com	15	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	10	53	4	4	POSITIVE	\N	2026-03-23 06:55:10.965742	94
66	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:10.972448	user86@ecom.com	3	[]	9	67	17	5	POSITIVE	\N	2026-03-23 06:55:10.972448	86
67	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:10.977088	user77@ecom.com	7	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	2	36	136	4	POSITIVE	\N	2026-03-23 06:55:10.977088	77
68	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:10.981819	user3@ecom.com	30	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	9	56	112	5	POSITIVE	\N	2026-03-23 06:55:10.981819	3
69	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:10.986199	user70@ecom.com	39	[]	1	44	41	5	POSITIVE	\N	2026-03-23 06:55:10.986199	70
70	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:10.989975	user76@ecom.com	35	[]	9	62	79	4	POSITIVE	\N	2026-03-23 06:55:10.989975	76
71	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:10.994256	user59@ecom.com	13	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	9	6	84	4	POSITIVE	\N	2026-03-23 06:55:10.994256	59
72	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:10.998877	user14@ecom.com	1	[]	9	36	89	5	POSITIVE	\N	2026-03-23 06:55:10.998877	14
73	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.004118	user65@ecom.com	13	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	6	86	62	4	POSITIVE	\N	2026-03-23 06:55:11.004118	65
74	Average product. Works as expected but nothing impressive. Might look for alternatives next time.	2026-03-23 06:55:11.016044	user76@ecom.com	14	[]	0	27	91	3	NEUTRAL	\N	2026-03-23 06:55:11.016044	76
75	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.020142	user6@ecom.com	14	[]	7	20	79	5	POSITIVE	\N	2026-03-23 06:55:11.020142	6
76	Assumenda dolorem sit praesentium numquam maxime a quisquam dolorem minima nostrum nostrum et deleniti non expedita error labore nisi et.	2026-03-23 06:55:11.034351	user89@ecom.com	31	["1.png", "2.png", "3.png"]	5	48	15	5	POSITIVE	\N	2026-03-23 06:55:11.034351	89
77	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.040012	user85@ecom.com	7	[]	3	37	108	5	POSITIVE	\N	2026-03-23 06:55:11.040012	85
78	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.04485	user20@ecom.com	18	["1.png", "2.png", "3.png"]	5	77	53	4	POSITIVE	\N	2026-03-23 06:55:11.04485	20
79	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.093849	user62@ecom.com	38	[]	6	6	112	5	POSITIVE	\N	2026-03-23 06:55:11.093849	62
80	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.108333	user47@ecom.com	46	[]	8	32	64	5	POSITIVE	\N	2026-03-23 06:55:11.108333	47
81	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.115172	user31@ecom.com	18	[]	2	17	3	4	POSITIVE	\N	2026-03-23 06:55:11.115172	31
82	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.12041	user6@ecom.com	9	[]	11	39	54	5	POSITIVE	\N	2026-03-23 06:55:11.12041	6
83	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.126834	user48@ecom.com	24	[]	6	18	68	5	POSITIVE	\N	2026-03-23 06:55:11.126834	48
84	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.131335	user58@ecom.com	33	[]	2	86	90	5	POSITIVE	\N	2026-03-23 06:55:11.131335	58
85	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.14053	user22@ecom.com	12	[]	7	28	104	5	POSITIVE	\N	2026-03-23 06:55:11.14053	22
86	Dolores quidem dolorum et est in quam aspernatur incidunt nulla quisquam consequatur blanditiis occaecati eum quaerat magnam dolorem.	2026-03-23 06:55:11.147235	user97@ecom.com	1	[]	8	67	58	5	POSITIVE	\N	2026-03-23 06:55:11.147235	97
87	Numquam deleniti illum voluptates quos esse rerum blanditiis atque repellendus autem ad illum reiciendis.	2026-03-23 06:55:11.16741	user87@ecom.com	9	[]	9	48	20	3	NEUTRAL	\N	2026-03-23 06:55:11.16741	87
88	Decent product for the price. Does the job but could be better. Shipping was a bit slow.	2026-03-23 06:55:11.177679	user24@ecom.com	14	[]	1	76	99	3	NEUTRAL	\N	2026-03-23 06:55:11.177679	24
89	Repellendus ex porro laboriosam earum deleniti facere magni dignissimos ea neque illo distinctio aspernatur deserunt.	2026-03-23 06:55:11.202331	user26@ecom.com	36	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	5	38	98	5	POSITIVE	\N	2026-03-23 06:55:11.202331	26
90	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.216081	user15@ecom.com	44	[]	9	49	93	5	POSITIVE	\N	2026-03-23 06:55:11.216081	15
91	Assumenda molestiae illum quae qui voluptatem non dolores repellat velit maiores quod reiciendis id et at asperiores nulla nam quo.	2026-03-23 06:55:11.241544	user75@ecom.com	22	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	1	65	59	4	POSITIVE	\N	2026-03-23 06:55:11.241544	75
92	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.251001	user76@ecom.com	23	[]	7	90	59	4	POSITIVE	\N	2026-03-23 06:55:11.251001	76
93	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.256795	user42@ecom.com	2	[]	3	15	82	4	POSITIVE	\N	2026-03-23 06:55:11.256795	42
94	The product is okay, but nothing special. It works as advertised but I expected a bit more quality.	2026-03-23 06:55:11.261524	user81@ecom.com	1	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	3	84	63	3	NEUTRAL	\N	2026-03-23 06:55:11.261524	81
95	Decent product for the price. Does the job but could be better. Shipping was a bit slow.	2026-03-23 06:55:11.266759	user20@ecom.com	48	[]	1	39	120	3	NEUTRAL	\N	2026-03-23 06:55:11.266759	20
96	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.278818	user79@ecom.com	40	[]	1	66	123	5	POSITIVE	\N	2026-03-23 06:55:11.278818	79
97	The product is okay, but nothing special. It works as advertised but I expected a bit more quality.	2026-03-23 06:55:11.285632	user52@ecom.com	41	[]	8	25	62	3	NEUTRAL	\N	2026-03-23 06:55:11.285632	52
98	Commodi consequatur numquam veritatis eos architecto facere hic ut consequatur molestiae sint nam ut earum velit nihil.	2026-03-23 06:55:11.291071	user32@ecom.com	37	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	8	71	54	5	POSITIVE	\N	2026-03-23 06:55:11.291071	32
99	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.304501	user77@ecom.com	25	[]	8	44	55	5	POSITIVE	\N	2026-03-23 06:55:11.305024	77
100	Vero voluptatem nobis harum quas dolores et a quod qui repudiandae deserunt est sit eligendi debitis voluptates iusto.	2026-03-23 06:55:11.309889	user90@ecom.com	28	[]	3	72	126	5	POSITIVE	\N	2026-03-23 06:55:11.309889	90
101	Aspernatur sit natus non eius quod laudantium maiores quas beatae nam voluptas cum sed repellat.	2026-03-23 06:55:11.315244	user62@ecom.com	13	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	1	52	106	4	POSITIVE	\N	2026-03-23 06:55:11.315244	62
102	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.321921	user47@ecom.com	16	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	9	51	8	5	POSITIVE	\N	2026-03-23 06:55:11.321921	47
103	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.327474	user78@ecom.com	36	[]	2	47	32	4	POSITIVE	\N	2026-03-23 06:55:11.327474	78
104	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.334333	user94@ecom.com	28	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	8	71	104	5	POSITIVE	\N	2026-03-23 06:55:11.334333	94
105	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.341489	user47@ecom.com	26	[]	3	19	103	4	POSITIVE	\N	2026-03-23 06:55:11.341489	47
106	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.348091	user13@ecom.com	38	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	3	41	123	5	POSITIVE	\N	2026-03-23 06:55:11.348091	13
107	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.353507	user15@ecom.com	24	[]	7	94	118	5	POSITIVE	\N	2026-03-23 06:55:11.353507	15
108	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.360206	user14@ecom.com	27	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	4	36	146	5	POSITIVE	\N	2026-03-23 06:55:11.360206	14
109	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.365173	user83@ecom.com	12	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	8	41	59	5	POSITIVE	\N	2026-03-23 06:55:11.365173	83
110	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.370611	user51@ecom.com	28	["1.png", "2.png", "3.png"]	7	25	75	5	POSITIVE	\N	2026-03-23 06:55:11.370611	51
111	Qui velit rem molestiae voluptatem quasi commodi fuga sit est neque voluptas eos nesciunt voluptas corporis maxime ad eligendi.	2026-03-23 06:55:11.385615	user2@ecom.com	2	["1.png", "2.png", "3.png"]	11	84	50	5	POSITIVE	\N	2026-03-23 06:55:11.385615	2
112	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.392085	user33@ecom.com	44	[]	10	73	15	5	POSITIVE	\N	2026-03-23 06:55:11.392085	33
113	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.397254	user79@ecom.com	7	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	5	37	7	5	POSITIVE	\N	2026-03-23 06:55:11.397254	79
114	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.403015	user83@ecom.com	25	[]	7	95	108	5	POSITIVE	\N	2026-03-23 06:55:11.403015	83
115	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.424492	user20@ecom.com	49	[]	0	50	104	4	POSITIVE	\N	2026-03-23 06:55:11.424492	20
116	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.435156	user73@ecom.com	14	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	11	55	94	5	POSITIVE	\N	2026-03-23 06:55:11.435156	73
117	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.44558	user73@ecom.com	11	[]	11	2	122	5	POSITIVE	\N	2026-03-23 06:55:11.44558	73
118	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.460381	user14@ecom.com	2	[]	8	8	96	4	POSITIVE	\N	2026-03-23 06:55:11.460381	14
119	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.47887	user94@ecom.com	18	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	3	54	101	4	POSITIVE	\N	2026-03-23 06:55:11.47887	94
120	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.486386	user22@ecom.com	47	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	11	47	24	4	POSITIVE	\N	2026-03-23 06:55:11.486386	22
121	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.490848	user33@ecom.com	6	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	8	95	130	5	POSITIVE	\N	2026-03-23 06:55:11.490848	33
122	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.495424	user36@ecom.com	27	["1.png", "2.png", "3.png"]	9	91	111	5	POSITIVE	\N	2026-03-23 06:55:11.495424	36
123	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.501146	user66@ecom.com	18	[]	2	56	67	5	POSITIVE	\N	2026-03-23 06:55:11.501146	66
124	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.505279	user67@ecom.com	21	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	0	71	43	5	POSITIVE	\N	2026-03-23 06:55:11.505279	67
125	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.510295	user100@ecom.com	31	[]	10	12	27	5	POSITIVE	\N	2026-03-23 06:55:11.510295	100
126	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.515265	user52@ecom.com	22	[]	3	33	56	5	POSITIVE	\N	2026-03-23 06:55:11.515265	52
127	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.520075	user51@ecom.com	8	[]	1	100	68	4	POSITIVE	\N	2026-03-23 06:55:11.520075	51
128	Average product. Works as expected but nothing impressive. Might look for alternatives next time.	2026-03-23 06:55:11.527273	user32@ecom.com	24	[]	1	64	51	3	NEUTRAL	\N	2026-03-23 06:55:11.527273	32
129	Placeat vitae ipsam non molestiae ipsa quasi laudantium et fugiat voluptatem sit atque omnis neque qui facere consequatur.	2026-03-23 06:55:11.536963	user34@ecom.com	46	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	9	85	5	5	POSITIVE	\N	2026-03-23 06:55:11.536963	34
130	The product is okay, but nothing special. It works as advertised but I expected a bit more quality.	2026-03-23 06:55:11.541842	user2@ecom.com	25	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	8	30	6	3	NEUTRAL	\N	2026-03-23 06:55:11.541842	2
131	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.546356	user71@ecom.com	5	[]	1	45	61	5	POSITIVE	\N	2026-03-23 06:55:11.546356	71
132	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.552613	user31@ecom.com	37	[]	3	22	109	5	POSITIVE	\N	2026-03-23 06:55:11.552613	31
133	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.557412	user59@ecom.com	0	[]	2	90	54	5	POSITIVE	\N	2026-03-23 06:55:11.557412	59
134	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.56208	user21@ecom.com	11	[]	4	22	7	4	POSITIVE	\N	2026-03-23 06:55:11.56208	21
135	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.567493	user92@ecom.com	41	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	2	34	119	4	POSITIVE	\N	2026-03-23 06:55:11.567493	92
136	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.571852	user50@ecom.com	49	[]	9	22	25	5	POSITIVE	\N	2026-03-23 06:55:11.571852	50
137	Average product. Works as expected but nothing impressive. Might look for alternatives next time.	2026-03-23 06:55:11.582257	user60@ecom.com	37	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	5	45	137	3	NEUTRAL	\N	2026-03-23 06:55:11.582257	60
138	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.58865	user84@ecom.com	43	[]	11	37	29	5	POSITIVE	\N	2026-03-23 06:55:11.58865	84
139	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.596579	user6@ecom.com	18	[]	4	97	88	5	POSITIVE	\N	2026-03-23 06:55:11.596579	6
140	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.60074	user91@ecom.com	28	[]	10	2	107	5	POSITIVE	\N	2026-03-23 06:55:11.60074	91
141	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.605795	user58@ecom.com	41	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	9	16	96	5	POSITIVE	\N	2026-03-23 06:55:11.605795	58
142	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.613762	user95@ecom.com	31	[]	10	24	135	5	POSITIVE	\N	2026-03-23 06:55:11.613762	95
143	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.619352	user99@ecom.com	4	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	3	51	77	5	POSITIVE	\N	2026-03-23 06:55:11.619352	99
144	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.624504	user47@ecom.com	23	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	0	27	89	5	POSITIVE	\N	2026-03-23 06:55:11.624504	47
145	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.629141	user93@ecom.com	1	["1.png", "2.png", "3.png"]	6	76	67	5	POSITIVE	\N	2026-03-23 06:55:11.629141	93
146	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.633475	user94@ecom.com	23	[]	10	92	44	4	POSITIVE	\N	2026-03-23 06:55:11.633475	94
147	Dolor velit exercitationem ab et commodi nemo et voluptas consectetur magnam libero et ut.	2026-03-23 06:55:11.637833	user64@ecom.com	29	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	9	77	29	3	NEUTRAL	\N	2026-03-23 06:55:11.637833	64
148	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.64272	user48@ecom.com	46	["1.png", "2.png", "3.png"]	8	64	49	4	POSITIVE	\N	2026-03-23 06:55:11.64272	48
149	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.647666	user53@ecom.com	39	[]	6	41	58	4	POSITIVE	\N	2026-03-23 06:55:11.647666	53
150	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.652326	user27@ecom.com	9	[]	2	98	86	5	POSITIVE	\N	2026-03-23 06:55:11.652326	27
151	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.657086	user8@ecom.com	30	[]	7	32	109	5	POSITIVE	\N	2026-03-23 06:55:11.657086	8
152	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.661392	user32@ecom.com	17	[]	8	23	142	4	POSITIVE	\N	2026-03-23 06:55:11.661392	32
153	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.666475	user25@ecom.com	16	[]	10	42	14	5	POSITIVE	\N	2026-03-23 06:55:11.666475	25
154	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.670937	user2@ecom.com	39	["1.png", "2.png", "3.png"]	7	88	29	5	POSITIVE	\N	2026-03-23 06:55:11.670937	2
155	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.676318	user96@ecom.com	24	["1.png", "2.png", "3.png"]	1	16	44	5	POSITIVE	\N	2026-03-23 06:55:11.676318	96
156	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.680584	user30@ecom.com	24	[]	9	47	11	5	POSITIVE	\N	2026-03-23 06:55:11.680584	30
157	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.685548	user78@ecom.com	6	[]	0	39	18	5	POSITIVE	\N	2026-03-23 06:55:11.685548	78
158	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.690372	user9@ecom.com	24	["1.png", "2.png", "3.png"]	10	21	3	5	POSITIVE	\N	2026-03-23 06:55:11.690372	9
159	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.694224	user41@ecom.com	34	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	1	56	45	4	POSITIVE	\N	2026-03-23 06:55:11.694224	41
160	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.700202	user19@ecom.com	2	[]	4	51	41	5	POSITIVE	\N	2026-03-23 06:55:11.700202	19
161	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.70516	user42@ecom.com	22	[]	0	49	139	4	POSITIVE	\N	2026-03-23 06:55:11.70516	42
162	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.709901	user5@ecom.com	19	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	4	10	125	5	POSITIVE	\N	2026-03-23 06:55:11.709901	5
163	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.713783	user53@ecom.com	0	[]	11	49	29	5	POSITIVE	\N	2026-03-23 06:55:11.713783	53
164	Decent product for the price. Does the job but could be better. Shipping was a bit slow.	2026-03-23 06:55:11.722507	user90@ecom.com	32	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	9	56	129	3	NEUTRAL	\N	2026-03-23 06:55:11.722507	90
165	Average product. Works as expected but nothing impressive. Might look for alternatives next time.	2026-03-23 06:55:11.727253	user85@ecom.com	47	[]	6	82	137	3	NEUTRAL	\N	2026-03-23 06:55:11.727253	85
166	Autem et atque id nesciunt in pariatur quo laboriosam quidem earum nihil eum ipsam voluptatem.	2026-03-23 06:55:11.731878	user100@ecom.com	29	[]	7	86	119	4	POSITIVE	\N	2026-03-23 06:55:11.731878	100
167	Suscipit dolor natus molestias et facilis debitis tenetur rerum ducimus et nobis sed quia ea sint nihil ratione.	2026-03-23 06:55:11.736125	user56@ecom.com	31	[]	2	30	98	4	POSITIVE	\N	2026-03-23 06:55:11.736125	56
168	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.740926	user32@ecom.com	10	["1.png", "2.png", "3.png"]	7	97	55	5	POSITIVE	\N	2026-03-23 06:55:11.740926	32
169	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.74512	user70@ecom.com	48	[]	7	40	13	5	POSITIVE	\N	2026-03-23 06:55:11.74512	70
170	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.749909	user23@ecom.com	38	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	8	73	134	5	POSITIVE	\N	2026-03-23 06:55:11.749909	23
171	Deleniti totam ea molestiae explicabo et dolorum ea velit placeat repellendus eaque sed sed non et deserunt.	2026-03-23 06:55:11.754128	user85@ecom.com	27	["1.png", "2.png", "3.png"]	6	94	75	5	POSITIVE	\N	2026-03-23 06:55:11.754128	85
172	Really happy with this purchase. Good quality, fair price, and fast delivery. What more could you ask for?	2026-03-23 06:55:11.762727	user95@ecom.com	7	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	3	93	116	5	POSITIVE	\N	2026-03-23 06:55:11.762727	95
173	Illum autem fugit atque harum reprehenderit beatae quas voluptatem laboriosam expedita qui dolor.	2026-03-23 06:55:11.768843	user67@ecom.com	46	[]	5	70	40	3	NEUTRAL	\N	2026-03-23 06:55:11.768843	67
174	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.773661	user60@ecom.com	15	[]	4	26	116	4	POSITIVE	\N	2026-03-23 06:55:11.773661	60
175	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.779022	user78@ecom.com	11	[]	6	35	67	5	POSITIVE	\N	2026-03-23 06:55:11.779022	78
176	The product is okay, but nothing special. It works as advertised but I expected a bit more quality.	2026-03-23 06:55:11.78359	user63@ecom.com	48	[]	2	22	67	3	NEUTRAL	\N	2026-03-23 06:55:11.78359	63
177	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.789104	user61@ecom.com	23	[]	2	36	109	5	POSITIVE	\N	2026-03-23 06:55:11.789104	61
178	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.802149	user85@ecom.com	30	[]	6	32	117	5	POSITIVE	\N	2026-03-23 06:55:11.802149	85
179	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.810895	user65@ecom.com	17	[]	5	69	71	4	POSITIVE	\N	2026-03-23 06:55:11.810895	65
180	Average product. Works as expected but nothing impressive. Might look for alternatives next time.	2026-03-23 06:55:11.827196	user43@ecom.com	46	[]	11	84	45	3	NEUTRAL	\N	2026-03-23 06:55:11.827196	43
181	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.832338	user73@ecom.com	19	[]	3	63	17	5	POSITIVE	\N	2026-03-23 06:55:11.832338	73
182	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.837325	user40@ecom.com	12	[]	6	46	122	5	POSITIVE	\N	2026-03-23 06:55:11.837325	40
183	This product is amazing! The quality is excellent and it arrived quickly. Highly recommend to anyone looking for a great product.	2026-03-23 06:55:11.842574	user54@ecom.com	40	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	1	66	55	4	POSITIVE	\N	2026-03-23 06:55:11.842574	54
184	Great value for money. The product works perfectly and the customer service was excellent.	2026-03-23 06:55:11.847462	user65@ecom.com	8	[]	11	12	114	5	POSITIVE	\N	2026-03-23 06:55:11.847462	65
185	Modi alias odio omnis rerum voluptatem aut velit perspiciatis rerum et sit maxime id porro et corrupti sint nesciunt minima.	2026-03-23 06:55:11.85256	user15@ecom.com	37	[]	7	81	139	4	POSITIVE	\N	2026-03-23 06:55:11.85256	15
186	Average product. Works as expected but nothing impressive. Might look for alternatives next time.	2026-03-23 06:55:11.856678	user69@ecom.com	39	[]	7	4	121	3	NEUTRAL	\N	2026-03-23 06:55:11.856678	69
187	Average product. Works as expected but nothing impressive. Might look for alternatives next time.	2026-03-23 06:55:11.862593	user18@ecom.com	14	[]	5	97	80	3	NEUTRAL	\N	2026-03-23 06:55:11.862593	18
188	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.867614	user48@ecom.com	25	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	6	52	60	5	POSITIVE	\N	2026-03-23 06:55:11.867614	48
189	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.872494	user30@ecom.com	10	[]	7	85	102	4	POSITIVE	\N	2026-03-23 06:55:11.872494	30
190	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.878036	user74@ecom.com	9	[]	0	58	129	5	POSITIVE	\N	2026-03-23 06:55:11.878036	74
191	Quibusdam nulla molestiae atque sit non voluptatem blanditiis nam nobis omnis et soluta itaque hic.	2026-03-23 06:55:11.883378	user61@ecom.com	41	[]	2	100	48	5	POSITIVE	\N	2026-03-23 06:55:11.883378	61
192	Eum consequatur libero aperiam doloribus omnis ex odit id eum maxime eligendi aut sequi molestiae similique.	2026-03-23 06:55:11.888212	user47@ecom.com	36	[]	10	91	110	5	POSITIVE	\N	2026-03-23 06:55:11.888212	47
193	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.892511	user96@ecom.com	37	[]	7	83	136	4	POSITIVE	\N	2026-03-23 06:55:11.892511	96
194	Best purchase I've made in a while. Quality is top-notch and it does exactly what it's supposed to do.	2026-03-23 06:55:11.897802	user94@ecom.com	39	["1.png", "2.png", "3.png"]	2	20	113	5	POSITIVE	\N	2026-03-23 06:55:11.897802	94
195	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.902854	user18@ecom.com	25	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	3	42	141	5	POSITIVE	\N	2026-03-23 06:55:11.902854	18
196	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.906579	user12@ecom.com	15	["1.png", "2.png", "3.png", "1.png", "2.png", "3.png"]	8	11	13	5	POSITIVE	\N	2026-03-23 06:55:11.906579	12
197	I love this product! It's exactly what I was looking for. Fast shipping and great packaging too.	2026-03-23 06:55:11.910319	user89@ecom.com	40	[]	1	80	131	5	POSITIVE	\N	2026-03-23 06:55:11.910319	89
198	Very impressed with the quality. Exactly as described and even better in person. Will definitely buy again!	2026-03-23 06:55:11.91432	user83@ecom.com	11	[]	3	5	85	4	POSITIVE	\N	2026-03-23 06:55:11.91432	83
199	Absolutely fantastic! Exceeded my expectations in every way. Would give 6 stars if I could.	2026-03-23 06:55:11.918324	user49@ecom.com	47	[]	5	8	75	5	POSITIVE	\N	2026-03-23 06:55:11.918324	49
200	Dolores fuga cumque voluptas labore quam ullam illo accusantium aspernatur voluptatem deserunt dolorum sit voluptatem qui et.	2026-03-23 06:55:11.923762	user42@ecom.com	6	[]	2	78	46	4	POSITIVE	\N	2026-03-23 06:55:11.923762	42
201	asdasdasdasdasd	2026-04-07 20:20:29.001248	huynhminhthang246@gmail.com	0	[]	0	2	14	5	NEUTRAL	0.5	2026-04-07 20:20:29.001248	102
202	san pham qua te	2026-04-07 20:20:40.887728	huynhminhthang246@gmail.com	0	[]	0	3	15	5	NEUTRAL	0.5	2026-04-07 20:20:40.887728	102
205	san pham nhu cc	2026-04-07 20:55:40.679176	huynhminhthang246@gmail.com	0	[]	0	8	15	5	NEUTRAL	0.5	2026-04-07 20:55:40.679176	102
206	san pham nhu cc	2026-04-07 21:10:03.529063	huynhminhthang246@gmail.com	0	[]	0	7	14	5	NEUTRAL	0.5	2026-04-07 21:10:03.529063	102
207	sadasasdasdasdasdasd	2026-04-07 21:49:18.634037	huynhminhthang246@gmail.com	0	[]	0	10	15	5	NEUTRAL	0.5729	2026-04-07 21:49:18.634037	102
208	san pham nhu cc 	2026-04-07 21:50:47.30794	huynhminhthang246@gmail.com	0	[]	0	11	15	5	POSITIVE	0.6864	2026-04-07 21:50:47.30794	102
209	sß║ún phß║⌐m dß╗í tß╗ç	2026-04-19 20:43:43.261771	huynhminhthang246@gmail.com	0	[]	0	14	15	5	NEUTRAL	0.5	2026-04-19 20:43:43.261771	102
210	Sß║ún phß║⌐m qu├í tß╗æt	2026-04-19 20:46:37.415939	huynhminhthang246@gmail.com	0	[]	0	15	15	5	POSITIVE	0.9956	2026-04-19 20:46:37.415939	102
211	Sß║ún phß║⌐m rß║Ñt tß╗æt 	2026-05-12 14:52:11.598844	22130251@st.hcmuaf.edu.vn	0	[]	0	17	15	5	POSITIVE	0.9956	2026-05-12 14:52:11.598844	112
212	sß║ún phß║⌐m qu├í tß╗æt	2026-06-07 12:44:29.691398	huynhminhthang246@gmail.com	0	[]	0	18	14	5	POSITIVE	0.9956	2026-06-07 12:44:29.691398	102
213	Sß║ún phß║⌐m tß╗æt	2026-06-07 13:40:24.092533	22130251@st.hcmuaf.edu.vn	0	[]	0	20	14	5	POSITIVE	0.9932	2026-06-07 13:40:24.092533	116
\.


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reviews_id_seq', 213, true);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: reviews uk_review_user_product_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT uk_review_user_product_order UNIQUE (user_id, product_id, order_id);


--
-- Name: reviews ukr8vcm6neix10qorxt37o37kd8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT ukr8vcm6neix10qorxt37o37kd8 UNIQUE (user_id, product_id, order_id);


--
-- PostgreSQL database dump complete
--

\unrestrict IZXZWCYm3UXp2rbYVbtKZyhN04INOZQ01dRA4NdNmQWqh0mi8oZIKZYoPWXdUVm

