--
-- PostgreSQL database dump
--

\restrict bWkAQnvm7ySAapZuIHvuvkEjcWNudhIkaBvAzbQJBRPIEYlxOIpGRkzlPMFnC4T

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg12+1)
-- Dumped by pg_dump version 17.7 (Debian 17.7-3.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.otp_codes DROP CONSTRAINT IF EXISTS fkt9j4to767daef0ws3fiixis0y;
ALTER TABLE IF EXISTS ONLY public.user_role DROP CONSTRAINT IF EXISTS fkt7e7djp752sqn6w22i6ocqy6q;
ALTER TABLE IF EXISTS ONLY public.user_role DROP CONSTRAINT IF EXISTS fkj345gk1bovqvfame88rcx7yyx;
ALTER TABLE IF EXISTS ONLY public.addresses DROP CONSTRAINT IF EXISTS fk1fa36y2oqhao3wgg2rw1pi459;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.user_role DROP CONSTRAINT IF EXISTS user_role_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS ukr43af9ap4edm43mmtq01oddj6;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;
ALTER TABLE IF EXISTS ONLY public.roles DROP CONSTRAINT IF EXISTS roles_pkey;
ALTER TABLE IF EXISTS ONLY public.otp_codes DROP CONSTRAINT IF EXISTS otp_codes_pkey;
ALTER TABLE IF EXISTS ONLY public.addresses DROP CONSTRAINT IF EXISTS addresses_pkey;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.user_role;
DROP TABLE IF EXISTS public.roles;
DROP TABLE IF EXISTS public.otp_codes;
DROP TABLE IF EXISTS public.addresses;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.addresses (
    address_id bigint NOT NULL,
    building_name character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    district_id integer,
    district_name character varying(255),
    is_default boolean,
    pincode character varying(255) NOT NULL,
    province_id integer,
    province_name character varying(255),
    state character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    ward_code character varying(255),
    ward_name character varying(255),
    user_id bigint
);


--
-- Name: addresses_address_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.addresses ALTER COLUMN address_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.otp_codes (
    otp_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    is_used boolean NOT NULL,
    otp_code character varying(6) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: otp_codes_otp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.otp_codes ALTER COLUMN otp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_codes_otp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    role_name character varying(20),
    CONSTRAINT roles_role_name_check CHECK (((role_name)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_SELLER'::character varying, 'ROLE_ADMIN'::character varying])::text[])))
);


--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_role (
    user_id bigint NOT NULL,
    role_id integer NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    email character varying(50) NOT NULL,
    image_url character varying(255),
    is_active boolean NOT NULL,
    password character varying(120) NOT NULL,
    username character varying(255) NOT NULL
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: addresses; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.addresses (address_id, building_name, city, country, district_id, district_name, is_default, pincode, province_id, province_name, state, street, ward_code, ward_name, user_id) FROM stdin;
4	41147 Suite 671	North Latanya	Canada	\N	\N	f	73121-6295	\N	\N	Hawaii	631 Schoen Rapid	\N	\N	2
5	210 Suite 959	Fritschview	Democratic People's Republic of Korea	\N	\N	f	71207	\N	\N	New Mexico	250 Grant Meadows	\N	\N	2
6	39788 Suite 893	New Philip	Bahrain	\N	\N	f	74654	\N	\N	Iowa	96926 Tamekia Forks	\N	\N	3
7	97471 Apt. 970	Connellyberg	Nigeria	\N	\N	f	04788	\N	\N	Iowa	36135 Pfeffer Square	\N	\N	4
8	367 Suite 873	Lake Noel	Turkmenistan	\N	\N	f	94015-3426	\N	\N	Delaware	411 Renner Summit	\N	\N	4
9	5211 Apt. 516	Nolanville	Cote d'Ivoire	\N	\N	f	11912-6307	\N	\N	Connecticut	4203 Grimes Stream	\N	\N	5
10	81408 Suite 756	West Donettetown	Lithuania	\N	\N	f	17896	\N	\N	West Virginia	3349 Ethyl Isle	\N	\N	5
11	2559 Suite 162	Isidroside	Nigeria	\N	\N	f	47858-4331	\N	\N	Louisiana	6369 Mark Flat	\N	\N	6
12	37146 Suite 416	Thompsonshire	Belize	\N	\N	f	53880	\N	\N	Iowa	8927 Sawayn Stravenue	\N	\N	6
13	9728 Apt. 875	Port Mitchside	Cote d'Ivoire	\N	\N	f	55112-1428	\N	\N	California	19372 Stiedemann Spur	\N	\N	7
14	1512 Apt. 804	Roobchester	Canada	\N	\N	f	26211-0760	\N	\N	New Mexico	2712 Evangeline Isle	\N	\N	7
15	1099 Apt. 136	Adellchester	Monaco	\N	\N	f	59926-0766	\N	\N	Virginia	1744 Heidenreich Crossroad	\N	\N	8
16	8751 Suite 092	West Jamalborough	Malawi	\N	\N	f	57763	\N	\N	New Hampshire	03997 Runte Plain	\N	\N	8
17	120 Apt. 194	South Antoinemouth	Mali	\N	\N	f	72529-0865	\N	\N	Iowa	4993 Raymundo Path	\N	\N	9
20	72170 Suite 597	Levifurt	Dominica	\N	\N	f	44184-0863	\N	\N	Iowa	9953 Doyle Crest	\N	\N	11
21	7081 Apt. 843	New Caleb	Rwanda	\N	\N	f	70924	\N	\N	South Carolina	90769 Fritsch Centers	\N	\N	11
22	89947 Apt. 797	Milfordmouth	Saint Martin	\N	\N	f	54319	\N	\N	Wyoming	97477 Tromp Drives	\N	\N	12
23	4944 Suite 468	South Alethea	Nigeria	\N	\N	f	61011-3610	\N	\N	Maine	928 Tracy Via	\N	\N	13
24	11555 Suite 985	New Lynn	Guinea	\N	\N	f	89125	\N	\N	Virginia	350 Eugene Junctions	\N	\N	13
25	296 Apt. 125	South Imelda	Belize	\N	\N	f	76193	\N	\N	Colorado	3885 Reichert Drives	\N	\N	13
26	46893 Apt. 967	Haleyville	Saint Kitts and Nevis	\N	\N	f	42240-9623	\N	\N	New Mexico	655 Hane Haven	\N	\N	14
27	68603 Suite 026	South Celesta	Jersey	\N	\N	f	65683-0423	\N	\N	Maryland	6226 Vance Fords	\N	\N	14
28	3040 Apt. 947	Bartellborough	Senegal	\N	\N	f	40948	\N	\N	Indiana	52963 Pedro Union	\N	\N	15
29	231 Suite 862	Raynorshire	Czech Republic	\N	\N	f	63819	\N	\N	Rhode Island	5768 Schamberger Loop	\N	\N	15
30	957 Suite 226	West Paulinabury	Saint Barthelemy	\N	\N	f	77187-0259	\N	\N	Missouri	553 Wintheiser Field	\N	\N	16
31	94574 Suite 592	North Steven	Tonga	\N	\N	f	19969	\N	\N	Michigan	111 Domingo Pines	\N	\N	16
32	67320 Suite 571	South Chesterchester	Madagascar	\N	\N	f	47234	\N	\N	Louisiana	409 Greenholt Cliff	\N	\N	17
33	896 Suite 056	West Brookmouth	Austria	\N	\N	f	46795	\N	\N	Utah	0615 Bauch Common	\N	\N	17
34	7519 Apt. 216	Lake Nickolasland	Estonia	\N	\N	f	11311-1814	\N	\N	Hawaii	48986 Pollich Expressway	\N	\N	17
35	8476 Suite 357	New Janeyberg	Papua New Guinea	\N	\N	f	66451-3710	\N	\N	Texas	024 Julio Village	\N	\N	18
36	5626 Apt. 362	Weissnatmouth	Dominican Republic	\N	\N	f	00466-7000	\N	\N	Ohio	504 Sandie Ville	\N	\N	18
37	4209 Apt. 425	Carmeloburgh	Italy	\N	\N	f	96305	\N	\N	New Jersey	78463 Melina Square	\N	\N	19
38	1848 Apt. 350	Audryfort	Cayman Islands	\N	\N	f	61220	\N	\N	New York	7924 Kirlin Trail	\N	\N	19
39	376 Suite 811	North Augustinehaven	Cape Verde	\N	\N	f	56653	\N	\N	Wisconsin	986 Sharda Circle	\N	\N	19
40	62253 Apt. 777	Bernhardland	Malaysia	\N	\N	f	07798	\N	\N	Minnesota	73359 Shin Mill	\N	\N	20
41	68638 Apt. 165	North Lynnashire	Vanuatu	\N	\N	f	15938-2398	\N	\N	Georgia	352 Edwin Ports	\N	\N	20
42	7889 Apt. 969	Lake Lia	Haiti	\N	\N	f	47669	\N	\N	Oklahoma	0404 Devon Plaza	\N	\N	20
43	65071 Apt. 501	Port Margaretteshire	Cyprus	\N	\N	f	46410-3070	\N	\N	Nevada	471 Rempel Valley	\N	\N	21
44	69643 Suite 340	Lake Micah	Namibia	\N	\N	f	55989-9660	\N	\N	North Dakota	3707 Pfannerstill Corners	\N	\N	22
45	376 Apt. 250	East Marveltown	Jordan	\N	\N	f	89913-0803	\N	\N	Massachusetts	6194 Theron Garden	\N	\N	23
46	9594 Apt. 196	Legrosfort	Burkina Faso	\N	\N	f	62652	\N	\N	Maryland	2164 Schmidt Parkways	\N	\N	23
47	361 Suite 094	Lake Caritamouth	Lithuania	\N	\N	f	04112-3043	\N	\N	Arizona	18749 Robert Estates	\N	\N	24
48	7045 Suite 105	Halvorsonton	Cape Verde	\N	\N	f	30154-1302	\N	\N	Connecticut	199 Macejkovic Radial	\N	\N	24
49	00851 Apt. 705	Tylerville	Japan	\N	\N	f	63372	\N	\N	Wisconsin	2491 Ted Park	\N	\N	25
50	261 Suite 343	Lake Jeromeview	Cote d'Ivoire	\N	\N	f	28072-9103	\N	\N	Indiana	7131 Roberts Extension	\N	\N	25
51	93112 Suite 801	Port Shaunland	Turks and Caicos Islands	\N	\N	f	27814	\N	\N	Alaska	626 Langworth Union	\N	\N	26
52	934 Suite 563	Rosenbaumside	French Southern Territories	\N	\N	f	78043	\N	\N	North Dakota	559 Barton Passage	\N	\N	26
53	07112 Suite 348	East Alia	Turkmenistan	\N	\N	f	71210-2787	\N	\N	Delaware	36965 Hilton Via	\N	\N	26
54	159 Apt. 395	Hayesburgh	Fiji	\N	\N	f	30290	\N	\N	Louisiana	1387 Hector Locks	\N	\N	27
55	9686 Suite 444	Marianoton	Bouvet Island (Bouvetoya)	\N	\N	f	99643-2585	\N	\N	Nevada	2198 Dannette Knolls	\N	\N	28
56	7669 Apt. 092	West Jerrellview	Azerbaijan	\N	\N	f	76163	\N	\N	North Dakota	7223 Gaylord Fall	\N	\N	28
57	3262 Suite 513	Charlenamouth	Croatia	\N	\N	f	49427-7722	\N	\N	Connecticut	58780 Davis Bridge	\N	\N	29
58	7957 Suite 650	East Cesarburgh	Jersey	\N	\N	f	76013-6718	\N	\N	West Virginia	1662 Carla Villages	\N	\N	29
59	13309 Apt. 927	Purdyfurt	French Guiana	\N	\N	f	04557-5724	\N	\N	Idaho	560 Graham Groves	\N	\N	30
60	6256 Suite 848	Wilmerburgh	Mozambique	\N	\N	f	00136	\N	\N	Texas	0231 Ratke Radial	\N	\N	30
61	773 Suite 257	New Margitview	Saint Barthelemy	\N	\N	f	13784-9268	\N	\N	Florida	6201 Lacy Drives	\N	\N	31
62	5902 Apt. 808	Marquisport	Kiribati	\N	\N	f	56803-1511	\N	\N	Iowa	9582 Lasandra Throughway	\N	\N	32
63	41827 Suite 570	East Marlynhaven	Austria	\N	\N	f	91599	\N	\N	Iowa	04981 Paris Mission	\N	\N	32
64	49634 Apt. 999	Florenebury	Niue	\N	\N	f	43413	\N	\N	Colorado	3610 Rutherford Points	\N	\N	33
65	563 Apt. 986	Port Ruthport	Croatia	\N	\N	f	64915-5118	\N	\N	North Carolina	705 Rowe Lakes	\N	\N	33
66	29968 Suite 608	Bartonborough	Burundi	\N	\N	f	74190-6935	\N	\N	Utah	601 Macejkovic Manors	\N	\N	34
67	993 Apt. 583	Pollichfurt	Malta	\N	\N	f	26131-8132	\N	\N	Arizona	34222 Vickey Mill	\N	\N	35
68	4119 Suite 354	Harlanfort	Iceland	\N	\N	f	01529-4877	\N	\N	Wisconsin	643 O'Connell Square	\N	\N	35
69	12885 Suite 252	East Murrayville	Ecuador	\N	\N	f	13231	\N	\N	New Hampshire	4510 Bauch Run	\N	\N	36
70	84306 Apt. 682	Audiefort	Brazil	\N	\N	f	38124-1698	\N	\N	Tennessee	9469 Kerluke Key	\N	\N	36
71	184 Apt. 004	Harveyborough	Wallis and Futuna	\N	\N	f	51778	\N	\N	Connecticut	6547 Streich Knolls	\N	\N	37
72	3405 Suite 290	New Erniemouth	Kyrgyz Republic	\N	\N	f	74818	\N	\N	South Carolina	7690 Cremin Throughway	\N	\N	37
73	6562 Suite 918	Xavierfort	Equatorial Guinea	\N	\N	f	93509-3602	\N	\N	Nebraska	6307 Lind Tunnel	\N	\N	38
74	1840 Apt. 230	Lake Sirenashire	Palestinian Territory	\N	\N	f	63395	\N	\N	Maryland	4083 Anna Extension	\N	\N	38
75	50425 Suite 013	Damianborough	Iran	\N	\N	f	75903-6758	\N	\N	Tennessee	932 Lona Orchard	\N	\N	38
76	78934 Suite 574	Lake Donellachester	Jordan	\N	\N	f	41958-9821	\N	\N	Connecticut	575 Murazik Mountains	\N	\N	39
77	424 Apt. 060	New Vivienne	Guadeloupe	\N	\N	f	90970	\N	\N	Rhode Island	87444 Klara Ports	\N	\N	39
78	79231 Suite 384	Burmaview	United Arab Emirates	\N	\N	f	17035-1626	\N	\N	Idaho	68514 Fahey Brooks	\N	\N	40
79	2888 Apt. 392	Okunevaport	United Arab Emirates	\N	\N	f	38145-8592	\N	\N	New Jersey	5137 Zemlak Lake	\N	\N	40
80	46118 Apt. 071	Yundtton	Andorra	\N	\N	f	50218	\N	\N	Florida	2505 Durgan Isle	\N	\N	41
81	467 Apt. 383	Danielborough	New Caledonia	\N	\N	f	28710-3718	\N	\N	Mississippi	468 Rowe Plain	\N	\N	42
82	2904 Apt. 678	Robbyview	Cuba	\N	\N	f	82259	\N	\N	Oregon	9350 Joel Mount	\N	\N	42
83	109 Apt. 779	North Eleonorebury	Comoros	\N	\N	f	08887	\N	\N	New Mexico	805 Rudolph Crossroad	\N	\N	43
84	501 Apt. 376	Gayleshire	Guyana	\N	\N	f	37522	\N	\N	Ohio	8175 Lannie Creek	\N	\N	44
85	2792 Suite 337	New Royce	Guam	\N	\N	f	41455	\N	\N	Connecticut	5850 Bashirian Underpass	\N	\N	44
86	80322 Suite 915	West Cleo	Suriname	\N	\N	f	75811	\N	\N	Washington	600 Brynn Mountain	\N	\N	45
87	569 Suite 394	East Deloris	Liechtenstein	\N	\N	f	63037	\N	\N	California	860 McDermott Villages	\N	\N	45
88	65903 Apt. 835	West Simonaville	Solomon Islands	\N	\N	f	24529-3506	\N	\N	Tennessee	165 Rohan Garden	\N	\N	45
89	305 Suite 393	West Glenn	Anguilla	\N	\N	f	02240	\N	\N	Maine	667 Sharyl Mountains	\N	\N	46
90	508 Suite 771	Lake Roderickstad	Mexico	\N	\N	f	82232-4339	\N	\N	Hawaii	5259 Lily Walk	\N	\N	46
91	18551 Suite 682	Lishaton	Switzerland	\N	\N	f	96905-0815	\N	\N	Rhode Island	16346 Willian Drive	\N	\N	47
92	04460 Apt. 034	South Roslynland	Hungary	\N	\N	f	52234	\N	\N	Iowa	1383 Mose Crossroad	\N	\N	47
93	699 Apt. 823	Kleinfort	Saint Vincent and the Grenadines	\N	\N	f	02577-3277	\N	\N	Nevada	273 Robel Drive	\N	\N	47
94	608 Suite 850	Watsicaside	Vanuatu	\N	\N	f	79906-2841	\N	\N	Nebraska	82656 Malcolm Green	\N	\N	48
95	2037 Suite 980	Ratkeside	Mauritania	\N	\N	f	14663-2446	\N	\N	Indiana	250 Melaine Keys	\N	\N	49
96	152 Apt. 004	Romeomouth	Moldova	\N	\N	f	03407	\N	\N	Tennessee	735 Spencer Stream	\N	\N	49
97	91700 Apt. 194	Lake Darlenahaven	Tunisia	\N	\N	f	90294	\N	\N	Indiana	71271 Prohaska Center	\N	\N	50
98	6178 Suite 088	Hiramberg	Cook Islands	\N	\N	f	68791-7383	\N	\N	Louisiana	405 Nathanael Parkway	\N	\N	50
99	9920 Apt. 327	East Ollieport	Tonga	\N	\N	f	37838-0259	\N	\N	Utah	700 Schoen Cliff	\N	\N	50
100	208 Apt. 201	East Rodger	French Polynesia	\N	\N	f	40065	\N	\N	New Mexico	009 Pacocha Mountains	\N	\N	51
101	784 Suite 378	Lake Kacey	Yemen	\N	\N	f	16847-9643	\N	\N	South Dakota	71692 Skiles Locks	\N	\N	51
102	12573 Apt. 682	East Luciano	Mayotte	\N	\N	f	52856	\N	\N	Maine	8108 Collins Plaza	\N	\N	52
103	8480 Suite 098	New Raylene	Botswana	\N	\N	f	55786	\N	\N	Alabama	331 Rozanne Square	\N	\N	52
104	04071 Suite 822	Lake Norman	South Georgia and the South Sandwich Islands	\N	\N	f	14773	\N	\N	Wisconsin	404 Von Isle	\N	\N	53
105	9865 Suite 336	Earlland	Christmas Island	\N	\N	f	42714	\N	\N	Florida	462 Nitzsche Manor	\N	\N	53
106	64823 Apt. 129	Altenwerthmouth	Macedonia	\N	\N	f	81323	\N	\N	North Carolina	0830 Leo Parkways	\N	\N	53
107	30421 Apt. 413	New Hunter	Belgium	\N	\N	f	59061	\N	\N	Massachusetts	82784 Harry Mount	\N	\N	54
108	92961 Suite 728	Gorczanyberg	Belize	\N	\N	f	58795	\N	\N	Nebraska	521 Erin Keys	\N	\N	55
109	3435 Suite 560	Shaniquachester	Peru	\N	\N	f	83956-1902	\N	\N	Hawaii	77840 Carol Manors	\N	\N	56
110	6123 Apt. 807	Annelieseborough	Finland	\N	\N	f	15450	\N	\N	Oregon	6372 Hyatt Club	\N	\N	56
111	151 Apt. 012	Purastad	Paraguay	\N	\N	f	26110	\N	\N	Florida	0235 Mills Lock	\N	\N	57
112	3313 Apt. 762	Greenfort	Philippines	\N	\N	f	23621-3495	\N	\N	Michigan	511 Ronda Knoll	\N	\N	57
113	395 Suite 180	Ignaciotown	Denmark	\N	\N	f	24847	\N	\N	Louisiana	513 Kiehn Knolls	\N	\N	58
114	217 Apt. 393	North Henriettefurt	Pitcairn Islands	\N	\N	f	16135	\N	\N	New York	6924 Roma Common	\N	\N	59
115	2068 Apt. 321	Champlinville	Cook Islands	\N	\N	f	32503	\N	\N	Georgia	322 Kertzmann Island	\N	\N	59
116	1913 Apt. 752	Gusikowskihaven	Singapore	\N	\N	f	47117	\N	\N	New Jersey	0548 Jeanine Light	\N	\N	60
117	548 Apt. 537	Jeannineburgh	Greece	\N	\N	f	23823	\N	\N	Michigan	727 Pete Knoll	\N	\N	60
118	41321 Suite 121	Marylnside	Cook Islands	\N	\N	f	84341-9775	\N	\N	Arkansas	036 Hackett Gardens	\N	\N	61
119	76864 Apt. 092	Schmelershire	Western Sahara	\N	\N	f	96049-5322	\N	\N	Colorado	04759 Morar Port	\N	\N	61
120	07714 Apt. 005	Reenafurt	United States Minor Outlying Islands	\N	\N	f	21002-9604	\N	\N	Kansas	783 Steuber Harbors	\N	\N	62
121	3452 Suite 508	Port Vera	Uruguay	\N	\N	f	91993	\N	\N	Colorado	748 Nana Manor	\N	\N	63
122	6969 Suite 445	North Magdalenaburgh	Gabon	\N	\N	f	68392	\N	\N	Alabama	4777 Walter Glen	\N	\N	63
123	5261 Apt. 508	Otismouth	Czech Republic	\N	\N	f	92567-1216	\N	\N	New Jersey	6934 Fletcher Point	\N	\N	64
124	9006 Apt. 374	Jacobsonberg	Morocco	\N	\N	f	15478-1723	\N	\N	Idaho	2988 Hoeger Mountain	\N	\N	64
125	154 Suite 923	New Donnie	British Indian Ocean Territory (Chagos Archipelago)	\N	\N	f	72093	\N	\N	Vermont	5308 Steve Row	\N	\N	64
126	378 Apt. 173	Buckridgeport	Japan	\N	\N	f	08823-3511	\N	\N	Iowa	026 Jammie Pass	\N	\N	65
127	756 Apt. 848	Lake Blakeville	Rwanda	\N	\N	f	04092	\N	\N	Hawaii	15359 Allan Mountains	\N	\N	66
128	69350 Suite 837	Lynchchester	Tonga	\N	\N	f	44217	\N	\N	Indiana	665 Kurtis Island	\N	\N	67
129	71911 Suite 453	Omertown	Botswana	\N	\N	f	80954-3882	\N	\N	Mississippi	2524 Crooks Dale	\N	\N	67
130	76600 Suite 633	Macytown	Malta	\N	\N	f	51827-3578	\N	\N	North Carolina	0612 Clarice Camp	\N	\N	67
131	215 Apt. 020	Guadalupetown	Guernsey	\N	\N	f	96625	\N	\N	Arizona	005 DuBuque Common	\N	\N	68
132	56434 Suite 588	East Irisbury	Australia	\N	\N	f	22934-3066	\N	\N	Mississippi	0269 Shelli Row	\N	\N	68
133	615 Apt. 721	West Percyport	Netherlands Antilles	\N	\N	f	88485	\N	\N	North Carolina	146 Bahringer Roads	\N	\N	69
134	4111 Suite 942	Mirandastad	Aruba	\N	\N	f	45819	\N	\N	Illinois	92602 Winifred Rapid	\N	\N	70
135	010 Suite 432	South Raneeside	Singapore	\N	\N	f	35568-4407	\N	\N	Florida	6872 Bryant Common	\N	\N	70
136	72756 Suite 366	Lueilwitzburgh	Timor-Leste	\N	\N	f	52720	\N	\N	South Dakota	5819 Chasity Flats	\N	\N	71
137	949 Suite 519	South Suzy	British Indian Ocean Territory (Chagos Archipelago)	\N	\N	f	73501-5558	\N	\N	Illinois	87984 Cronin Villages	\N	\N	71
138	03519 Suite 533	Lake April	Cyprus	\N	\N	f	84243-7840	\N	\N	California	35877 Jamie Street	\N	\N	72
139	8582 Suite 084	Alanmouth	Kenya	\N	\N	f	12972	\N	\N	Maine	87463 Hand Walks	\N	\N	72
140	246 Apt. 850	New Claudettechester	Nepal	\N	\N	f	57825-4066	\N	\N	New Mexico	513 Simonis Underpass	\N	\N	73
141	6442 Apt. 459	Stehrburgh	Belgium	\N	\N	f	04943	\N	\N	Georgia	5072 Kory Street	\N	\N	73
142	50803 Apt. 368	West Ricardobury	United Arab Emirates	\N	\N	f	40413	\N	\N	Illinois	9995 Errol Viaduct	\N	\N	74
143	102 Suite 326	Port Reynaldashire	Bouvet Island (Bouvetoya)	\N	\N	f	37855	\N	\N	Kentucky	307 Medhurst Loop	\N	\N	74
144	103 Apt. 458	Dominickhaven	Cocos (Keeling) Islands	\N	\N	f	65265-1525	\N	\N	Alabama	5710 Amado Spur	\N	\N	75
145	6466 Suite 654	Damionborough	Sudan	\N	\N	f	30924	\N	\N	Illinois	7606 Hauck Fords	\N	\N	75
146	1850 Suite 453	Purdyberg	Moldova	\N	\N	f	28961-5683	\N	\N	Kansas	568 Gorczany Trail	\N	\N	76
147	047 Apt. 696	Frederichaven	Montenegro	\N	\N	f	03819	\N	\N	Vermont	32429 Beer Lodge	\N	\N	76
148	6123 Suite 794	Travischester	Russian Federation	\N	\N	f	12002	\N	\N	Alabama	303 Golda Curve	\N	\N	77
149	248 Suite 703	Luettgenchester	Uruguay	\N	\N	f	96141	\N	\N	West Virginia	6267 Gibson Fork	\N	\N	77
150	34148 Apt. 651	Arlinehaven	Turks and Caicos Islands	\N	\N	f	90859-3131	\N	\N	Georgia	9116 Jenkins Stravenue	\N	\N	78
151	6521 Apt. 862	North Elenora	Romania	\N	\N	f	87537	\N	\N	Colorado	85339 Gaylord Alley	\N	\N	79
152	5616 Suite 297	Blandamouth	Angola	\N	\N	f	33617-9879	\N	\N	Kentucky	62436 Jacobson Key	\N	\N	79
153	9782 Suite 630	East Lorenzaborough	Denmark	\N	\N	f	11211-7582	\N	\N	Michigan	470 Dietrich Glen	\N	\N	80
154	1665 Apt. 090	New Carl	Iran	\N	\N	f	63223	\N	\N	Oklahoma	05808 Buckridge Roads	\N	\N	80
155	51585 Suite 553	Lazarobury	Haiti	\N	\N	f	68475-1355	\N	\N	West Virginia	7776 Goyette Cliff	\N	\N	81
156	6362 Apt. 036	Port Trentland	Romania	\N	\N	f	30995-1401	\N	\N	Illinois	2495 Donnell Knoll	\N	\N	82
157	12732 Apt. 002	North Drucillaville	United States Minor Outlying Islands	\N	\N	f	60581	\N	\N	Wisconsin	87578 Rolando Islands	\N	\N	83
158	644 Apt. 738	West Patiencehaven	Poland	\N	\N	f	73529	\N	\N	Colorado	13045 Ruecker Burgs	\N	\N	84
159	72189 Apt. 336	East Teodoro	Madagascar	\N	\N	f	72667	\N	\N	Iowa	2511 Gorczany Plains	\N	\N	85
160	51805 Apt. 731	West Virgie	Grenada	\N	\N	f	40655-2426	\N	\N	Colorado	359 Emard Villages	\N	\N	85
161	792 Apt. 967	Peistad	Lesotho	\N	\N	f	05717-2566	\N	\N	Alabama	197 Carmelia Land	\N	\N	85
162	594 Suite 256	New Dorettamouth	Japan	\N	\N	f	05524	\N	\N	West Virginia	974 Leanora Plain	\N	\N	86
163	110 Suite 761	East Tieshabury	Thailand	\N	\N	f	64559	\N	\N	Rhode Island	14611 Cyril Isle	\N	\N	86
164	7021 Apt. 818	Annettaland	Rwanda	\N	\N	f	71578	\N	\N	Rhode Island	71338 Chung Circles	\N	\N	86
165	538 Apt. 454	South Clare	Thailand	\N	\N	f	73390-4607	\N	\N	Maine	926 Viva Mountains	\N	\N	87
166	398 Apt. 208	Muellershire	Chile	\N	\N	f	37796	\N	\N	Tennessee	75662 Robel Pike	\N	\N	88
167	321 Apt. 234	North Hugo	Israel	\N	\N	f	70656	\N	\N	Michigan	7701 Tromp Plains	\N	\N	88
168	56689 Apt. 100	Gavinport	Peru	\N	\N	f	65232	\N	\N	Texas	746 Miller Cove	\N	\N	88
169	35684 Apt. 510	Labadieville	Syrian Arab Republic	\N	\N	f	38354-2410	\N	\N	Oklahoma	89480 Ella Lake	\N	\N	89
170	376 Apt. 088	Hermistonbury	San Marino	\N	\N	f	18660	\N	\N	Washington	406 Anibal Course	\N	\N	90
171	00201 Apt. 130	Kingtown	Malta	\N	\N	f	34060-3775	\N	\N	Idaho	228 Goyette Spur	\N	\N	90
172	9135 Suite 389	West Daliaton	United Kingdom	\N	\N	f	97509-2706	\N	\N	Massachusetts	3611 Gerlach Pine	\N	\N	91
173	3213 Apt. 505	McGlynnview	Syrian Arab Republic	\N	\N	f	88543-4114	\N	\N	Montana	055 Jane Squares	\N	\N	92
174	4685 Apt. 785	Stiedemannmouth	Uzbekistan	\N	\N	f	88054-4487	\N	\N	Washington	708 Selena Mountain	\N	\N	92
175	0889 Suite 715	Shirleefort	Sri Lanka	\N	\N	f	00421-0684	\N	\N	Nebraska	946 Francisco Shore	\N	\N	93
176	01496 Suite 368	Aufderharport	South Georgia and the South Sandwich Islands	\N	\N	f	15979-0129	\N	\N	West Virginia	7817 Dare Viaduct	\N	\N	94
177	06713 Suite 476	Opheliaport	Tajikistan	\N	\N	f	11152	\N	\N	Maryland	11023 Rolfson Trace	\N	\N	94
178	472 Suite 525	Reillyville	Cuba	\N	\N	f	47897-2042	\N	\N	Hawaii	41411 Devon Trail	\N	\N	95
179	158 Apt. 960	Beatricemouth	Iceland	\N	\N	f	75701-0448	\N	\N	Nebraska	9915 Veum Gateway	\N	\N	95
180	9242 Apt. 118	Lake Keira	Republic of Korea	\N	\N	f	58296-7499	\N	\N	Iowa	4286 Lucienne Freeway	\N	\N	96
181	532 Suite 243	New Zola	Gibraltar	\N	\N	f	56665	\N	\N	Hawaii	796 Lanny Points	\N	\N	97
182	165 Suite 992	Port Monroe	Qatar	\N	\N	f	96358	\N	\N	South Carolina	2164 Boyce Stream	\N	\N	97
183	83355 Apt. 351	South Sammy	Faroe Islands	\N	\N	f	15533-9497	\N	\N	Oregon	230 Pearle Green	\N	\N	97
184	797 Apt. 747	Port Dirkmouth	Indonesia	\N	\N	f	20388	\N	\N	New Jersey	50149 Hilll Springs	\N	\N	98
185	554 Suite 363	East Andy	Senegal	\N	\N	f	51664-1591	\N	\N	Pennsylvania	993 Kessler Falls	\N	\N	99
186	905 Apt. 117	North Tonamouth	Saint Martin	\N	\N	f	21995	\N	\N	Michigan	28921 Delores Shoals	\N	\N	100
187	30509 Apt. 133	Kurtville	Ukraine	\N	\N	f	84685-2117	\N	\N	Kentucky	70656 Barrows Corner	\N	\N	100
1	882 Suite 636	Gulgowskiborough	Bosnia and Herzegovina	\N	\N	f	38810-7804	\N	\N	Nevada	60547 Hickle Junction	\N	\N	1
2	744 Apt. 597	North Elana	Afghanistan	\N	\N	f	04233	\N	\N	Florida	8847 Cyndy Isle	\N	\N	1
3	41741 Apt. 065	Alfonzomouth	Argentina	\N	\N	f	18486-5245	\N	\N	Missouri	618 Hand Orchard	\N	\N	1
188	12312312312312312	S╞ín La	Vietnam	2204	Huyß╗çn Quß╗│nh Nhai	t	70000	266	S╞ín La	Huyß╗çn Quß╗│nh Nhai	2619 Lourie Cove	140209	X├ú M╞░ß╗¥ng Sß║íi	1
192	LANDMARK 67	H├▓a B├¼nh	Vietnam	2156	Huyß╗çn Lß║íc S╞ín	f	70000	267	H├▓a B├¼nh	Huyß╗çn Lß║íc S╞ín	122 Nguyß╗àn HUß╗ç	230527	X├ú Xuß║Ñt H├│a	112
189	xcvxcvss	S╞ín La	Vietnam	3266	huyß╗çn Sß╗æp Cß╗Öp	f	70000	266	S╞ín La	huyß╗çn Sß╗æp Cß╗Öp	vxcvxc	800118	X├ú Sß╗æp Cß╗Öp	102
193	LANDMARK 67	L├áo Cai	Vietnam	2171	Huyß╗çn M╞░ß╗¥ng Kh╞░╞íng	t	70000	269	L├áo Cai	Huyß╗çn M╞░ß╗¥ng Kh╞░╞íng	vxcvxcgggg	80915	X├ú Thanh B├¼nh	116
\.


--
-- Data for Name: otp_codes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.otp_codes (otp_id, created_at, expires_at, is_used, otp_code, user_id) FROM stdin;
1	2026-03-18 14:27:22.221294+00	2026-03-18 14:37:22.221294+00	t	978228	102
2	2026-03-18 14:39:15.593129+00	2026-03-18 14:49:15.593129+00	t	149034	102
3	2026-03-18 14:42:16.256831+00	2026-03-18 14:52:16.256831+00	t	308605	102
4	2026-03-18 14:46:08.261213+00	2026-03-18 14:56:08.261213+00	t	450189	102
5	2026-03-18 14:46:31.325496+00	2026-03-18 14:56:31.325496+00	t	019735	102
6	2026-03-18 14:52:43.720961+00	2026-03-18 15:02:43.720961+00	t	161333	102
7	2026-03-18 14:54:36.592559+00	2026-03-18 15:04:36.592559+00	t	368399	102
8	2026-03-18 14:54:58.500133+00	2026-03-18 15:04:58.500133+00	t	739882	102
9	2026-03-18 14:58:41.600144+00	2026-03-18 15:08:41.600144+00	t	182098	102
10	2026-03-19 06:14:49.984346+00	2026-03-19 06:24:49.984346+00	t	500827	102
11	2026-03-19 06:31:34.647235+00	2026-03-19 06:41:34.647235+00	t	871900	102
12	2026-03-19 06:45:18.964835+00	2026-03-19 06:55:18.964835+00	t	497683	102
13	2026-03-29 06:38:56.122291+00	2026-03-29 06:48:56.122291+00	t	962085	102
14	2026-04-21 04:59:47.022413+00	2026-04-21 05:09:47.022413+00	t	698142	102
15	2026-04-21 05:00:42.632182+00	2026-04-21 05:10:42.632182+00	f	982680	102
16	2026-05-12 06:47:22.12757+00	2026-05-12 06:57:22.12757+00	t	036849	112
17	2026-06-07 05:39:34.272938+00	2026-06-07 05:49:34.272938+00	t	827331	113
18	2026-06-07 06:32:58.914306+00	2026-06-07 06:42:58.914306+00	t	107138	116
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles (role_id, role_name) FROM stdin;
1	ROLE_USER
2	ROLE_SELLER
3	ROLE_ADMIN
\.


--
-- Data for Name: user_role; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_role (user_id, role_id) FROM stdin;
2	1
3	2
3	1
4	2
4	1
5	1
6	2
6	1
7	1
8	1
9	1
11	1
12	1
13	1
14	1
15	1
16	1
17	2
17	1
18	1
19	1
20	2
20	1
21	1
22	1
23	1
24	1
25	2
25	1
26	1
27	1
28	1
29	1
30	1
31	1
32	1
33	1
34	2
34	1
35	1
36	2
36	1
37	2
37	1
38	1
39	1
40	1
41	2
41	1
42	2
42	1
43	2
43	1
44	1
45	1
46	1
47	1
48	2
48	1
49	1
50	1
51	2
51	1
52	1
53	1
54	2
54	1
55	1
56	1
57	1
58	1
59	1
60	1
61	1
62	1
63	1
64	1
65	1
66	1
67	1
68	2
68	1
69	1
70	1
71	1
72	1
73	1
74	2
74	1
75	1
76	2
76	1
77	1
78	1
79	1
80	2
80	1
81	2
81	1
82	1
83	1
84	1
85	1
86	1
87	1
88	2
88	1
89	1
90	2
90	1
91	1
92	1
93	1
94	1
95	2
95	1
96	1
97	1
98	1
99	1
100	1
101	1
101	2
1	1
1	2
1	3
103	1
104	2
104	3
104	1
102	1
102	2
105	3
105	1
105	2
106	3
106	1
106	2
107	3
107	1
107	2
108	3
108	1
108	2
109	1
110	1
112	1
113	1
114	2
114	1
115	2
115	1
116	1
117	2
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (user_id, email, image_url, is_active, password, username) FROM stdin;
1	admin@ecom.com	https://s3.amazonaws.com/uifaces/faces/twitter/ryanjohnson_me/128.jpg	t	$2a$10$ZyjCKzwcT3qpW9kB2qsv4uHsF.m1.dedC.KvMJHWGj41w0XJdQntq	admin
2	nick.monahan@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/kikillo/128.jpg	t	$2a$10$Ia5O0xD7eIOxKtA3WlY6X.6mFs/1O5ogPmjWiKBTXNyMDh0Thx20q	rodrigo.toy0
3	gena.altenwerth@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/h1brd/128.jpg	t	$2a$10$kdYfufq4wIfdYP2GrlDKmu1cE77oHqXKcuES69vjAwELKKUrXIJbG	nicolas.mcglynn1
4	patrick.lindgren@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/sreejithexp/128.jpg	t	$2a$10$/ovERmVKXMkHCEYvt09jjOSFX/2/8D7zLnvqsZ090t3O3/GDPy5Wa	evelina.will2
5	kermit.west@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/nsamoylov/128.jpg	t	$2a$10$z8sn9Mv8OY8q42fsk4F5.Og8QBqERJbMxkKcYR7xQHRNJoXzMQ/K.	isidra.schaefer3
6	shayla.wisoky@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/nellleo/128.jpg	t	$2a$10$CI8/kWIvgIUJkgOhmCbW7uJxsc5UdcJXPH5015n4OPqxMK3VwPxsy	perla.lemke4
7	galen.rice@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/derekcramer/128.jpg	t	$2a$10$BbuVt2.OXt7HS5dQY3yAJewDPK1zhKIifyNw43dBVuIx/NlD/jVyW	albert.moen5
8	morgan.bergnaum@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/bartoszdawydzik/128.jpg	t	$2a$10$p/oyxWX1dvvS1W0tWI5NReDHfTjy8L2V/j3M/dSbEdAas13vYgJja	manual.heller6
9	sharmaine.littel@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/mastermindesign/128.jpg	t	$2a$10$RGn.NbFv6skrbnU4gGMFn.CAjhbjjTpukWUtv.PC/IHUWWwb9boEa	eun.schmidt7
11	royce.marks@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/michaelabehsera/128.jpg	t	$2a$10$uuj1FcQQKh/DsTpYyAfWvORJKAE9FXd4UjTWWvtNV0mXTi2Mj1O4W	carolee.dickens9
12	roscoe.okuneva@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/madewulf/128.jpg	t	$2a$10$qNU320VEGI9iOMyFQtUMLeFIPJWZ4CbOC1tb7tLA/gSKqAy3HRr4O	shirley.olson10
13	charles.block@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/dpmachado/128.jpg	t	$2a$10$2gya4SFXAXwn4..YGc3k2uaUWwqC1HCODiayev6ZyKDiCfet/Ui4e	morris.reilly11
14	rosamaria.oconnell@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/incubo82/128.jpg	t	$2a$10$mHrp35SvDEePKIsSfaSptuFwGjbViU5YaWSXT9anXxFlmoze0fK5m	jody.lang12
15	micah.kub@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/Karimmove/128.jpg	t	$2a$10$ACAOZCmY2/bbvx8qZS5KYeqjenuEyUw.zfIruGhePswwrFGe0VBEm	earnestine.schamberger13
16	milford.blanda@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/mekal/128.jpg	t	$2a$10$PStIRVuycsLFMqP/sg3uVuSIBa3fSVUTOuCV9/pL31xLDIkqgYLbG	milton.boehm14
17	sammie.harris@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/andrewarrow/128.jpg	t	$2a$10$9TXswruEVGJQmOZ1sH6swO2idZ2AlOkF3doA8kX2EQshbuZhSXik.	ronald.blanda15
18	lynnette.walsh@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/benoitboucart/128.jpg	t	$2a$10$KR8u4opoqaqyOj0yqB0rn.cqb8ehK3mgyVHY64FLT9FaMVjorxSqS	harley.jerde16
19	dominick.ebert@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/benjamin_knight/128.jpg	t	$2a$10$zirHX1u2iLh.sRsPHVv4aeeuiFpaFnvDO2EOna7CykMmv8UeJJJEa	lionel.barton17
20	asley.mann@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/imomenui/128.jpg	t	$2a$10$pl.ou9Tg6IwQhsO101WNSO3Fdb1hWysDCL0DwvAk0MBieP3sjdlri	jeniffer.hintz18
21	ronny.kris@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/geneseleznev/128.jpg	t	$2a$10$dIrpHoRsQo0fwzTVPoGIteHGnCWkTlvnnvM.m8CKo3.5XsgvbzSHK	geraldo.gusikowski19
22	jamal.harris@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/shoaib253/128.jpg	t	$2a$10$oh77hxMbpsao7rUsyFtAH.dT7Y5RwB2klCpPRPFxXbHJq8MLtEtI.	rex.lueilwitz20
23	elliot.daugherty@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/derienzo777/128.jpg	t	$2a$10$VDAXnlojuzm6bgjBmdsz4.YWj6wvfqVUXyHRhPFk5NZhUGbkoWZaW	elke.donnelly21
24	maud.kovacek@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/jffgrdnr/128.jpg	t	$2a$10$c78FwiDs09lmnzf8/xwIe.BhQdPdvoLAVJns1zLztDK1CeyIvjLhO	shandi.cummings22
25	teodoro.shanahan@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/marclgonzales/128.jpg	t	$2a$10$Pv21YCJhOdM5Hu/0P0Ux0epjal9a65B5dmfTBfC8.F2feHRX12.cO	sharell.littel23
26	reed.thompson@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/llun/128.jpg	t	$2a$10$YmeEh.c1YWInInaVEkgWzeytbi9o2vSI6kiK4VyPuK8F/f5BkVGf2	margaretta.cronin24
27	dinah.bayer@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/gkaam/128.jpg	t	$2a$10$katm3Kjlt9bN.OaOUVvswe2978bb96DFKwYlhNEidicpN5D3yb32i	kandra.prosacco25
28	lindsay.ritchie@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/panchajanyag/128.jpg	t	$2a$10$V1z.mHwrqY9ARz2MT0Z9NOKZ1W8yqjnuMVUUImA33xPmLeTFgD.4y	annalee.oconnell26
29	veronica.von@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/daniloc/128.jpg	t	$2a$10$EfR2vXwfTpIsOSSqxPbm0eczavpszma141wE7uNUIR8LQe6ymIAEm	shin.abernathy27
30	kristofer.ziemann@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/joshhemsley/128.jpg	t	$2a$10$cuDXsndPR6kFIoZDrx//T.clUo4sO7RqZwlkn6XgpDvb15p9NS5Aq	trinh.jaskolski28
31	kerri.bahringer@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/rdbannon/128.jpg	t	$2a$10$S/S7TYqy1JLLpb8wRqyHXemAHqm9RRIsCZ4pI3yTvgcwm8ViJa/k.	dara.lowe29
32	herschel.kertzmann@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/herkulano/128.jpg	t	$2a$10$yzZdaFB6mVp.sqKgImHmmuSDQ7RwYR7Ss/Cu6VVzNimOSEq8kAi2e	beaulah.barton30
33	isaac.orn@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/nastya_mane/128.jpg	t	$2a$10$s8cXjuPAqwvr0yWuEW093uZJjOph0gYkCJ5s8HoKFscOSlJN4lNNW	jazmine.jacobson31
34	jacques.lakin@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/themadray/128.jpg	t	$2a$10$IjA51XiyxKwU/BbnrNAq/utSlgiBKIrZq6fQpsbTtzURJp68SMXFq	mozell.jakubowski32
35	an.hahn@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/josecarlospsh/128.jpg	t	$2a$10$lQwAO3PewteTLLfza3zH0OcECVRL6Su9RlR5wjNFAEp6CgM.cxYOu	gerry.stark33
36	valrie.brakus@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/leeiio/128.jpg	t	$2a$10$EXsZz2ZwQKK7g/e5s0qcGeme4CNMV1eTXdmUmkTB6BSgLtWZW5zM6	verona.carroll34
37	shon.beahan@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/bartjo/128.jpg	t	$2a$10$cJIZjAla/U3vKiu.aYqK9eSLluIxXSsfd9PjyipLKAUaLwuyhHWMG	janay.dickinson35
38	cory.klein@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/albertaugustin/128.jpg	t	$2a$10$X87FGA9ymBSAyiRW8g/7JOl5XErydEbuiZSEU6XpNB.IGrDq7k3/W	latina.ward36
39	sarina.ankunding@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/dhilipsiva/128.jpg	t	$2a$10$4j6Yod0Zn1VSgrZEp/UVKuYNLFTp7/kfRKkxByTGGOOyMidN3OI8m	emmanuel.predovic37
40	roslyn.lakin@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/tomas_janousek/128.jpg	t	$2a$10$8FDpgbFe/CH3r5pU4GurpuMFcymJXJliBpbliRsLM43x0bMcY3cdu	damian.harris38
41	britany.bogisich@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/_yardenoon/128.jpg	t	$2a$10$OR/c4TA3TBD./ZLiwRG6euQw/SgldAG3Yfc39Bsctek4NECwWyacy	marjory.zboncak39
42	margaret.russel@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/_dwite_/128.jpg	t	$2a$10$.JdAPNHGn8uCrnrn7Kgir.si5kuUB5BJbi8TpSoQogweUz6x0mt4m	haywood.jenkins40
43	gladys.conn@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/polarity/128.jpg	t	$2a$10$gxl5ngEK0piw4zt5FJSYw.U.9EHOjlsrrKZpe8A1hUFKyzf4Mi0ZC	cherie.lueilwitz41
44	lindsey.mills@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/nerrsoft/128.jpg	t	$2a$10$2HmiLYa7kBW96VWXsjtlg.e407EHw0Q5fXgraf04tQ4y9BZ1PsZ/y	lyman.langosh42
45	jacinto.koelpin@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/tereshenkov/128.jpg	t	$2a$10$DPGt4F22j9UjGroOwOtwHOWNwThLfI3mEi8/jwU.cSw6HE/OncrzS	vilma.frami43
46	reda.murazik@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/lanceguyatt/128.jpg	t	$2a$10$9C/N/v2i8K2AIWvb8MvLBORbV4R0wC7IKQSyMrBiicU9F7pjWNcdq	harold.stamm44
47	kenny.keebler@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/j_drake_/128.jpg	t	$2a$10$abE5ItjGyLpmqwHInQLBmO8ES7zLLsk.wrwZ2KJfhIZtK6Wz0.7V.	ira.kutch45
48	elia.walsh@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/karlkanall/128.jpg	t	$2a$10$NvdSDiuI25UXT0H/m8kNkumWcVOO1JudnCIU86T8TpwvzfS0.6yz2	nadine.rau46
49	ethan.rippin@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/kerihenare/128.jpg	t	$2a$10$LtkB8A1BZhB/TMLJwRQpneACeQO4I9OY5yPfrblDihQ1cdYwgYPJG	paulene.schmidt47
50	reita.zieme@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/blakesimkins/128.jpg	t	$2a$10$gY8bx37Tbw2D/6QU1NYxpek.zF3.lwU2slbX/mcXPM9aNWY21V/G.	ezra.windler48
51	seth.murazik@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/rickyyean/128.jpg	t	$2a$10$nPzY9S/CKD38lR4roykA5.fF6gWrI3A0VxPMtmDBW.DVSYe7HwMPi	jere.watsica49
52	gayle.schmitt@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/ah_lice/128.jpg	t	$2a$10$T1Nf1ZFG2qufFttruSKMrObWYu4zlTU7Kpamd7/5SZFCpaREB65wi	allen.braun50
53	boris.murphy@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/wintopia/128.jpg	t	$2a$10$jWVwr34.P05k42XoUY3dZ.7nZ/TUBnad/TjYrRw2gw829QHccAaGi	erik.grimes51
54	aron.bayer@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/snowshade/128.jpg	t	$2a$10$yx30fkRagg2/hEsOdTETPeRjzqP08s85e.B5vcoCFpmMzV1qLr/s.	stefan.feeney52
55	antonetta.jacobi@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/operatino/128.jpg	t	$2a$10$yUEaRq/nayVmaaGr5cQVTO19JrJ7VcUB9HvHJxWxG6vFMShWMSSpG	refugia.kshlerin53
56	lawerence.rutherford@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/samscouto/128.jpg	t	$2a$10$0HJvYv4zo02DNP.6SQA/1eVkQvX2BmmC9aro49wIZa.jv.PDUkTUu	delma.zieme54
57	caryn.lemke@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/oktayelipek/128.jpg	t	$2a$10$ZUtlt20hz9AO2EhNWdJm8./B4rDtbYmN8Noi4Z6CYp6Wz/Aah3bt.	salome.torphy55
58	edmund.rath@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/jamiebrittain/128.jpg	t	$2a$10$ZqLOaJ5lEb7SscwPcU6HIek3BkslOlysr9PJsD7Acb9Q4hNqFfTtK	graig.schulist56
59	keva.thiel@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/isnifer/128.jpg	t	$2a$10$MJCKSwVDgFtncJEzViXi9.Fq8SzGEwvOX6lFFJHGwZ8A6mlFcntue	randy.oberbrunner57
60	clair.price@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/marclgonzales/128.jpg	t	$2a$10$yZifNPiNETXLvLqU4wxzNOFIE6NbZ38BJPPVS2j8Qjk.SKh2y3w7.	odette.hermann58
61	jesenia.okon@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/lowie/128.jpg	t	$2a$10$UjiWi1XBF.KaaiHc1zjn7OsDVYd6FfgRL1JavlLCs0HPf3I73Knya	jacki.mann59
62	terra.hartmann@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/kamal_chaneman/128.jpg	t	$2a$10$frg7UUVnif7zZ1Mh0YWoGeZMhWD5ZH6Rc8P7SThlayXmG1dcGaYAW	epifania.lesch60
63	santana.frami@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/alek_djuric/128.jpg	t	$2a$10$2RGW9i57.Y3s42a5PfilSeiO.BwMZeGWaTkNd425I9w96SkV7XU2K	billy.hartmann61
64	cecelia.lind@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/lu4sh1i/128.jpg	t	$2a$10$GmLxYyaCttM7IcxZu8fJmuV2pexoRL9XENckNeTpj5CZH16VyiLF.	janene.hauck62
65	zetta.doyle@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/timothycd/128.jpg	t	$2a$10$21Kjywhjhl1WkzaVSiGtY.15lyPKcdRccn.OEQibxr/00Razyltxy	michael.kohler63
66	rocio.mckenzie@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/bartoszdawydzik/128.jpg	t	$2a$10$gr2bMKlI2t3fEbuFWOlW/O494EDK/Y4HIjXJbeu2Nhk.gtWylKrQ2	shara.streich64
67	angila.greenholt@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/mr_shiznit/128.jpg	t	$2a$10$lJLwnAkSOXgqPNaFePxqbuNFkaKX/jW5riDFrQDKXyxmYFcF7N3Xe	cami.hintz65
68	cristina.rohan@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/oksanafrewer/128.jpg	t	$2a$10$GkHIBClWmv0TRBfDTPMDAejKpQBWHQgE4EvmaGfw3xluSeJG4K6iW	genaro.hansen66
69	allan.ferry@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/kvasnic/128.jpg	t	$2a$10$zljO4AQzUz6aw9Egk5y8o.UKierWNUfSdG85IVz8chxHN1kibKKPu	twyla.tremblay67
70	wally.kris@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/salvafc/128.jpg	t	$2a$10$ePmofZC/LNiWBDEft7gusu0wNEUF4AJ9d9aorWQXQedli2wOCxKoS	rufus.mcclure68
71	stevie.hickle@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/davidsasda/128.jpg	t	$2a$10$GaRT6qPCoas9bzCvCRqo4.NrQ4pOPl0JGT1IvjJtuksMb8oThC0f6	nigel.kassulke69
72	desmond.senger@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/buryaknick/128.jpg	t	$2a$10$wpRMQRtEt9.ZQDKtqPD.c.UsHIn0FxfSfLcCK7Sc6Ggxw1COwp.1K	vance.rutherford70
73	denis.bernier@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/thewillbeard/128.jpg	t	$2a$10$np6gaJ19RVAVuItAz5Hp9eZHMai1Rqb7SmoQW.ztsRolEmJhkktci	hiram.casper71
74	christel.grimes@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/allagringaus/128.jpg	t	$2a$10$o9vAe1nU5HbXSm/I/eehpOKnhcye8KF0YB5rxJbz0B1Dw5aJo7iiu	erin.muller72
75	lien.gerlach@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/panghal0/128.jpg	t	$2a$10$nSBqf4QPTibIOBw4q4DDFOiOAgzQV6NOQvbXFe3Dtiz85zbGWdJii	robin.lind73
76	bertie.stoltenberg@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/harry_sistalam/128.jpg	t	$2a$10$CO8bChMn6q3X/wNCXc.yuuXxa6QB4PsnB14CTOzTQ7xVnqbTRNOIa	florance.mayert74
77	darci.kuhic@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/lebronjennan/128.jpg	t	$2a$10$zj1Ijke/udypm6UOFQ1jcOGtLqdX81KYXCvXL4H3kvO9JhpnH.KC.	judson.heller75
78	kathi.shanahan@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/mutlu82/128.jpg	t	$2a$10$6xeG3Ph02eIlbDX3DdwGC.jC3VATTHms.H0G9VfIEw5i6MiCzbPCO	dara.cormier76
79	rosalva.gislason@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/8d3k/128.jpg	t	$2a$10$HD/X3dg84pzgVjzQB60Tj.tvuMEGz1iE/njpIcZO2yTv6.ZtZZXlm	socorro.corwin77
80	dannie.schulist@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/weavermedia/128.jpg	t	$2a$10$GTmZl4HM1L8IUKSdsof.0.1bCLnzglCsumcb5AobPQXnRjUzHfIOy	belen.morar78
81	deeanna.rohan@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/normanbox/128.jpg	t	$2a$10$g/PNAM/48NtIztuqx6Sf9uO0Dt1.9zTIZwZCOUaBZJm7OfijlTzGe	randy.abernathy79
82	rubi.hartmann@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/joshmedeski/128.jpg	t	$2a$10$kXuX2lYMsXA3ZddJpZBUVu.ZN/a7d9z4m1hnmKccvKvGYSQtkwsAe	latrina.carroll80
83	marisha.kozey@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/id835559/128.jpg	t	$2a$10$XuwCfVVWCwX.cq/QnP0d6O9OSeg8Jlidq6dyu01ck/0ksjULpGc2m	demetra.champlin81
84	ashley.bogan@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/mvdheuvel/128.jpg	t	$2a$10$68v3xgJTZAKj6JQ7OavaduG.1PBQKpIT.NuTsTIb6OuW8mQL9J6bG	robin.wehner82
85	bobbie.bailey@hotmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/stefanotirloni/128.jpg	t	$2a$10$2KDlCEJO9CtlOmOzNqn3JOOf3D84dGARhev9ASCtKm0d9eQ1dXvBS	buddy.daniel83
86	anette.little@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/harry_sistalam/128.jpg	t	$2a$10$fsr7B8Co27D6hHK5BZP/QOMK/BTX0nRMIU66rVTTYyuOH5beIlHbq	darrick.marks84
87	randolph.gutmann@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/samscouto/128.jpg	t	$2a$10$b1jpFMpnyMrXSvRRvAcDoOJtkf9ZR1veuOjURbPMEyl3MFoaPN96G	raphael.nienow85
88	pennie.beier@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/daniloc/128.jpg	t	$2a$10$P4pnloeoXj6jwh7Gdh7e..Ex28xp7Ic5QU70/a8I2A0CPbnajR0da	cecil.fritsch86
89	joshua.vandervort@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/bertboerland/128.jpg	t	$2a$10$h.4n8pO2UKUVseK.JJXWpO26sxjzLhArRhP4G0lwNUPEzncWtojdS	suzanne.barton87
90	kristeen.beer@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/nastya_mane/128.jpg	t	$2a$10$vnX0QpMgxjtMjIbc6cuGFOEjJOq2udMn.BUCn2ZOeYRBCFXpx/UF.	chelsey.lindgren88
91	david.lemke@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/peter576/128.jpg	t	$2a$10$lxtgFYjsnFYPDGKGryL0XO4QWgG8tgRBYJz9/NoG5mewVpr9HsxOu	dale.hane89
92	stacey.wunsch@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/spacewood_/128.jpg	t	$2a$10$OdtI9lTL8rrqZij4mLuLT.KXTe/JcTOTS4fdJH4dWHNy.Cx7ekWi6	suzan.bergnaum90
93	burl.will@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/privetwagner/128.jpg	t	$2a$10$kTsp8QXS66NGVhzzdJDiZOfk8R9dbipsSnYXXxPVqsMTxLuMGLd0y	foster.gislason91
94	perry.leuschke@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/thaodang17/128.jpg	t	$2a$10$OrHiOqNOFPFudW4Y6WQRWe5aV9BiCxNIFFLhEVEmQx/5knA2jVmy2	hershel.homenick92
95	leopoldo.kshlerin@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/anatolinicolae/128.jpg	t	$2a$10$dUk3lCW4Z6mGM0knzBiTxOcP9GPZhIxGdhSqfQiV/pVaY4V30ev/W	scot.schumm93
96	scotty.volkman@gmail.com	https://s3.amazonaws.com/uifaces/faces/twitter/mahdif/128.jpg	t	$2a$10$ZZWX1u9i8QNw3e1PazWDEek6CcOYT4cxCoLogA5Mr438xfMMi72FS	lorriane.weissnat94
97	jan.ernser@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/nyancecom/128.jpg	t	$2a$10$SEDHVtxaq82CgxbrpO7W8ungFVuaufeTV9QqHETMufZ8wdPATiXGu	santos.kreiger95
98	deborah.veum@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/knilob/128.jpg	t	$2a$10$vTbkIzu1aUyIxJdvmViuTuAI7XOWtH0vLsiHJ1JGmAq63GsE8./fC	jimmy.swaniawski96
99	forrest.mertz@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/jeremyworboys/128.jpg	t	$2a$10$lyJ06Qqs1cd5qvFuliPKU.EZGsgbXJM9QDMl3AZscn4h7kH3cBGrG	carolina.predovic97
100	cletus.keeling@yahoo.com	https://s3.amazonaws.com/uifaces/faces/twitter/elisabethkjaer/128.jpg	t	$2a$10$msXu5U1fTKL.FrRKTSy0De4Kc4xEBGt0kSspiUm88j5CPc9EQXi/a	adriene.heaney98
101	ViHanh@gmail.com		t	$2a$10$9fFWaW6zIla5rYt4YLlwfOHrzZKYIV.rV1xixIAEMbndFuyDnSpZ2	ViHandShop
112	22130252@st.hcmuaf.edu.vn	31343C.svg	t	$2a$10$WmfiNz16yXC8aif3/WhmbOcT7MiG.VMy/z1Yo63XvKFwSHgRyhNaC	huynhminhthang24
103	test@test.com	31343C.svg	t	$2a$10$et2NBzBpAMGWjrLak9n8HOvovAGeKgsxEiky3CJoSTEt/FkAd3CEa	testuser
116	22130251@st.hcmuaf.edu.vn	31343C.svg	t	$2a$10$dkxCMV0mvb5dB0bVDeQ0XehYBgq5rGKGRgeakTkPbosRlbNxnINla	thang123gggggsadasdasd
104	sarahconoordz@gmail.com		t	$2a$10$F6WcSoe7NMHs7zz4jVEPYeL9pTXPlHD6aQIf65v2WFj.nFSt4J/Eq	WW174FFD
105	victory@123.com		t	$2a$10$aKYWTU51gOI3m/gE1iqPbuQ4TPMMMbbZB5Dw3FnUSJ0GImfnUdE46	victory
106	clone123@gmail.com		t	$2a$10$/l0.mDhzEh25JItDfNglJ.2cDblBVQWLabkqsJR/toG3dZKSaC9tO	clone123
107	clone124@gmail.com		t	$2a$10$UNK0u05t/7CglXLyUAeNR.9BXdiFx1F00NmABikM1lRpcZnbHz0de	clone124
108	clone125@gmail.com		t	$2a$10$IAQesR9p.qr0uzezlnxan.8lSwMSCyEunwcFtGLTzMCzOu0tuwTT2	clone125
102	huynhminhthang246@gmail.com	31343C.svg	t	$2a$10$POUFRY.4RMIHExBGRG5Hxurvc2Pehebx3LGG7/.DFQdNWnRmARa/O	thang
109	victory@1234.com		t	$2a$10$2VxudfrJFX6OYlo91dThzOg6TnYRszOyudkmHUWJMXVj2V6OcuE2e	victory24
110	huynhminhthang247@gmail.com	31343C.svg	t	$2a$10$TpSTdg2QLC2ZUBcPlzzdSOFHHdbEorvi3q0jkIkwhdcG9fXn8RId6	thang123
114	asdasdasd@123.com		t	$2a$10$rcB/HrFApFXoeScoy3FgL.6gYGa4yfEep7qrudYD0ErmhAN/PaWuK	WWQV04H9
117	asdasdeeaaa@gmail.com		t	$2a$10$jwwAiXRDWYeWSCtInvZFtu3jCwH//ivII3rd9jvhXtP7yvyV.AfUa	WWQV04H91aaa
115	asdasdea@123.com		t	$2a$10$PXyJn736olKLyQ3KCnpPIOlYVFbPIh5.FozdQ91KmZdA/rxLxO7Ne	WWQV04H10
113	22130253@st.hcmuaf.edu.vn	31343C.svg	t	$2a$10$6nN6PR8nwGMaHqZ4oT4iaetsu.zNr6bh7Cuz0FLNOam/o7F9RYc.m	thang12121
\.


--
-- Name: addresses_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.addresses_address_id_seq', 193, true);


--
-- Name: otp_codes_otp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.otp_codes_otp_id_seq', 18, true);


--
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 3, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_id_seq', 117, true);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (address_id);


--
-- Name: otp_codes otp_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_codes
    ADD CONSTRAINT otp_codes_pkey PRIMARY KEY (otp_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: user_role user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: addresses fk1fa36y2oqhao3wgg2rw1pi459; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT fk1fa36y2oqhao3wgg2rw1pi459 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_role fkj345gk1bovqvfame88rcx7yyx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_role fkt7e7djp752sqn6w22i6ocqy6q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkt7e7djp752sqn6w22i6ocqy6q FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- Name: otp_codes fkt9j4to767daef0ws3fiixis0y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.otp_codes
    ADD CONSTRAINT fkt9j4to767daef0ws3fiixis0y FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict bWkAQnvm7ySAapZuIHvuvkEjcWNudhIkaBvAzbQJBRPIEYlxOIpGRkzlPMFnC4T

