package com.ecom.analytics.config;

import com.ecom.analytics.dto.TrackEventDTO;
import com.ecom.analytics.entity.UserEvent;
import org.modelmapper.ModelMapper;
import org.modelmapper.PropertyMap;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class BeanConfig {

    @Bean
    public ModelMapper modelMapper() {
        ModelMapper mapper = new ModelMapper();
        
        // Configure mapping from TrackEventDTO to UserEvent
        // Skip the id field since it's auto-generated by the database
        mapper.addMappings(new PropertyMap<TrackEventDTO, UserEvent>() {
            @Override
            protected void configure() {
                skip(destination.getId());
            }
        });
        
        return mapper;
    }
}
