spring:
  application:
    name: gateway-service
  app:
    jwtSecret: "mySecret123"
    jwtExpirationMs: 600000
    jwtCookieName: "ecom"
  config:
    import: optional:configserver:http://localhost:8888
