spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot_db
    username: ${DB_USER:fragile}
    password: ${DB_PASSWORD:204863}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

gemini:
  model:
    chat: gemini-2.5-flash
    embedding: gemini-embedding-001
  embedding:
    dimensions: 768
    sync-interval: 3600000

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.ecom.chatbot: DEBUG
    org.springframework.web: INFO
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
