spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbot
    username: ${DB_USER:fragile}
    password: ${DB_PASSWORD:204863}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  ai:
    vertex:
      ai:
        gemini:
          project-id: gen-lang-client-0858695901
          location: "europe-west1"
          model: "gemini-2.0-flash-lite"
        embedding:
          project-id: gen-lang-client-0858695901
          location: "asia-east1"
    mcp:
      server:
        type: SYNC
        annotation-scanner:
          enabled: true

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.ecom.chatbot: DEBUG
    org.springframework.web: INFO
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7